### ISSUE TITLE
Erlang/OTP images are unmaintained and should be removed from the official images list

### ISSUE THREAD

**Issue by RoadRunnr** [docker-library/official-images#10064]
The only maintenance happening on those image is upgrading the Erlang versions.

The owners/maintainers do not respond in any way to valid issues or pull requests. The images should therefore be considered unmaintained and hence remove from the list official images.

**Comment by yosifkit** [comment]
> Version bumps and security fixes should be attended to in a timely manner.

Our requirements for maintainership are fairly low since we don't want to impose arbitrary rules on other organizations that might not fit with their release cycles. From our perspective, the `erlang` images are maintained and kept up-to-date.

We don't have specific requirements for maintainers on how active they are to issues/PRs in their own repos, that is up to them.  Possibly, in this case, the GithHb [`erlang`](https://github.com/erlang) org might have some governance/ownership, but I don't know if they have any formal governance requirements on their repositories.
