### ISSUE TITLE
Can't mount docker volume for /var/lib/mysql in OSX user directory

### ISSUE THREAD

**Issue by snowwolf007cn** [docker-library/official-images#1067]
I try to apply "-v $HOME/develop/docker-volume/var/lib/docker-mysql:/var/lib/mysql" for mysql:latest, the container is created normal, but mysqld won't start, after "docker logs", I found that it's because of the permission problem. 
I can apply "-v $HOME/develop/docker-volume/etc/docker-mysql/conf.d:/etc/mysql/conf.d" to the container and run the image properly.
I can do it on Fedora 21,  but not on OSX.

Is it a bug need to be fixed?

**Comment by tianon** [comment]
Sorry for the delay; https://github.com/docker-library/mysql would be a better place to report this issue.  In this case though, the problem is that on OSX, you're using boot2docker in a VM, so `$HOME` is in the shared storage, and modifying permissions there isn't going to work.  See also https://github.com/docker-library/mysql/issues/99 for a good thread discussing this problem specifically in the context of MySQL. :+1:
