### ISSUE TITLE
Having issues with ubuntu:14.04

### ISSUE THREAD

**Issue by jakirkham** [docker-library/official-images#1110]
No longer able to build this image ( https://github.com/jupyter/notebook/blob/master/Dockerfile ) since the last update of `ubuntu:14.04`. It appears `apt-get` got messed up somehow. See example here ( https://circleci.com/gh/jakirkham/notebook/39 ). I didn't see this issue an hour ago.

**Comment by jakirkham** [comment]
FWIW, I think this may be an upstream issue. It is being reported by other users, who, I don't believe are using this image. ( http://askubuntu.com/questions/682413/error-getting-dependencies-for-matplotlib ) ( https://bugs.launchpad.net/linuxmint/+bug/1503604 ) However, it would still be nice to rollback to the last version until this is resolved.

**Comment by jakirkham** [comment]
Maybe related ( https://groups.google.com/d/msg/python-dirbtuves/M2dMoxZH6XE/4d-8-PuCM3QJ ).

**Comment by jakirkham** [comment]
It turns out the issue is the minimal version of python blocks us from installing a development version of python. We now have a workaround.

**Comment by mikedoug** [comment]
Yes, I've done a bit more research.

So here's the problem.  The Dockerfile is using the root file system provided by https://partner-images.canonical.com/core/trusty/.  The 20150925 and 20151001 builds of the Ubuntu 14.04 (Trusty) cloud image have a fubared Python installation with a mix of Python 3.4.3 and Python 3.4.0.  (You can see that in the manifest, look for the `python` lines: https://partner-images.canonical.com/core/trusty/20150925/ubuntu-trusty-core-cloudimg-arm64.manifest)

On 2015-10-07 (two days ago), the maintainers of the Ubuntu Docker image updated their root file system with the 20151001 build from Canonical.  This broke the Python 3 installation such that you could no longer install the python dev packages because of mismatched versions.

Canonical has provided a new build today (20151009) where they have reverted to a pure Python 3.4.0 installation (no more mismatch!).  Once they update the Docker image to use this cloud image root file system, then all will be well with the ubuntu:14.04 Docker image.  Until then, hard code your docker base image to ubuntu:trusty-20150814 if you want a working Python 3 installation.

It'd also be nice if someone with some weight could contact Canonical and find out what the heck is going on.  This isn't the first time Python 3.4.3 has leaked into the cloud images and has caused us no end of problems when it flopped back.

**Comment by jakirkham** [comment]
If someone is going to contact them, it would be nice if they could discuss this bug again ( https://bugs.launchpad.net/ubuntu/+bug/920601 ). I tried using this workaround ( http://askubuntu.com/a/454302 ), but hit this issue ( https://bugs.launchpad.net/ubuntu/+source/langpack-locales/+bug/931717 ). If the image already has the workaround run, this might not be a problem. Or if it is fixed on the Ubuntu end that would be nicer still.

**Comment by tianon** [comment]
The upstream bug is https://bugs.launchpad.net/bugs/1505164 -- images are rebuilt, and PR is open at https://github.com/docker-library/official-images/pull/1114.
