### ISSUE TITLE
Latest version of Crate not found

### ISSUE THREAD

**Issue by mikethebeer** [docker-library/official-images#1192]
Hi,
i have made a PR today and it got merged (22 hours ago). https://github.com/docker-library/official-images/pull/1188

However, if I pull this image the result is the following:
```
docker pull crate:0.52.2
Pulling repository docker.io/library/crate
Tag 0.52.2 not found in repository docker.io/library/crate
```
In the official docker-hub repo of `crate` the latest versions are correct (see https://hub.docker.com/_/crate/)

Thanks for your time. Looking forward to here from you.

Regards,
Michael

**Comment by tianon** [comment]
Hey Michael, sorry about that -- we're technically in a "pushing
moratorium" while the Automated Build servers get some work done (when we
push some images it's kind of rough on them right now, which is what's
being worked on), and that's why the update isn't up yet but I don't think
pushing "crate" is going to break much, so I've got it building/pushing
right now. :+1:

**Comment by mikethebeer** [comment]
Hi @tianon,
thanks for the fast answer - it works now :dancer:
