### ISSUE TITLE
Any official OCI Image Annotations?

### ISSUE THREAD

**Issue by ecki** [docker-library/official-images#12580]
The README seems to not talk about `MAINTAINER` (Or the OCI.authors replacement) should it be skipped?

the README does not discuss [OCI image annotations](https://github.com/opencontainers/image-spec/blob/main/annotations.md) (LABELS), should there be any? org.opencontainers.image.title etc?

**Comment by tianon** [comment]
Since we use `docker build`, we don't actually have a way to set OCI image annotations, but see https://github.com/docker-library/official-images/issues/3540#issuecomment-530925319 for our thoughts on `LABEL`s (which are stored in a different/older place from proper OCI annotations, inside the image config itself), especially:

> We don't actively recommend using labels. If an image maintainer wants to have labels, that is fine, but label names should adhere to the image spec: https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md
