### ISSUE TITLE
Official Images don't seem to be getting rebuilt when base image changes

### ISSUE THREAD

**Issue by ceejatec** [docker-library/official-images#12641]
For instance, the `couchbase:6.6.5` image was last updated 4 months ago: https://hub.docker.com/layers/couchbase/library/couchbase/6.6.5/images/sha256-02a08c0d00ee19dac6652145fd6f6afbb243fef8b4edea071ed39c99f68f0495?context=explore

That image is based on `ubuntu:20.04`: https://github.com/couchbase/docker/blob/b9ef0fefa25a0ca646bf746765f66bf33ee3fac7/enterprise/couchbase-server/6.6.5/Dockerfile#L3

But ubuntu:20.04 was last updated 8 days ago: https://hub.docker.com/layers/ubuntu/library/ubuntu/20.04/images/sha256-b2339eee806d44d6a8adc0a790f824fb71f03366dd754d400316ae5a7e3ece3e?context=explore

My understanding was that Docker would automatically rebuild Official Images when their base image was updated, and that appears to be happening for our newer images, but not all of them.

**Comment by tianon** [comment]
In the case of 6.6.5 specifically, this is going to be due to https://github.com/docker-library/official-images/pull/12094#issuecomment-1080376201 (as far as I know, they were never updated -- see also the failing CI on the most recent PR: https://github.com/docker-library/official-images/pull/12369).

The discussion in https://github.com/docker-library/official-images/pull/12094#issuecomment-1074533034 is also very much related.

Looking at https://hub.docker.com/_/couchbase?tab=tags, that's consistent as all the 7.x tags are updated.

**Comment by ceejatec** [comment]
I did wonder if that might be the cause; thanks for the confirmation. Would it be possible for the named administrators of Official Images to get an email notification when one of their builds starts failing?

I did come up with an (ugly) workaround for this problem that I believe should work for 6.6.5 and community-6.6.0 as well; I'll try to propose that soon.

**Comment by ceejatec** [comment]
Pull request to update older images: https://github.com/docker-library/official-images/pull/12649
