### ISSUE TITLE
Missing rockylinux:latest

### ISSUE THREAD

**Issue by daviesrob** [docker-library/official-images#12797]
@NeilHanlon The rockylinux:latest tag was removed in commit 5306230e99ba5d59126657d7e62559f103db50f2. Is that supposed to have happened, and if not could it be restored, please?

**Comment by NeilHanlon** [comment]
Hi @daviesrob  - It was intentional, and I'll share a bit on why. In your case, I would suggest that you use the rockylinux:8 tag to specifically pull in the rockylinux/8 container image.

My reasoning for removing the latest tag was to prevent any ambiguity as to what version of Rocky Linux was being used. For example, now that we have two major versions available, which would be the 'latest'? If we set the latest major (9) to latest, that would affect a lot of people who are using the latest tag to pull in 8.x as they would be pulling in a completely different version of the operating system. On the other hand, leaving the latest tag on 8 would run counter to the documentation we provide which states the latest tag will point to the most recent major release.

After considering it, I figured that removing the tag entirely and updating the documentation (in progress) would be the most reasonable path which would adversely affect the fewest amount of users of the images. I do apologize that the change was not communicated on time, that is my fault and I will work on having some updated documentation and a news post over the weekend on this topic.

Please let me know if there's anything else I can help you with, or if there are any clarifications I can provide.

Best,
Neil

**Comment by tianon** [comment]
Closing per https://github.com/docker-library/docs/pull/2170 and/or in favor of https://github.com/rocky-linux/sig-cloud-instance-images/issues/31 :+1:
