### ISSUE TITLE
How are autobuilds supported?

### ISSUE THREAD

**Issue by endophage** [docker-library/official-images#1281]
We want to publish the official Notary images using autobuilds. This allows us to have a bleeding edge version (aka nightly build, but really, even more frequently) pinned to the latest tag with versioned releases individually git-tagged and built via an additional autobuild rule.

We're looking to get notary on a CI cycle at least out to docker's staging servers so autobuilds are pretty much the only option. I'd rather not maintain 2 hub repos with the same tags and it doesn't seem like the official images process is really designed around the idea of having nightly builds.

cc @cyli @NathanMcCauley @diogomonica

**Comment by psftw** [comment]
Autobuilds are not supported because it would break the existing pull request gatekeeper process, and there are also technical reasons such as autobuilds not being able to cache layers.  The official repository process may be able to support nightly builds or other cycles if it's really needed (in such a way that the Dockerfile can't be arbitrarily changed).  It doesn't make sense to treat an official repository like a CI build.  In cases where a CI-style build is needed, using autobuilds independently with a separate Hub repository would work.

**Comment by endophage** [comment]
I get what you're saying, but there are plenty of companies that release official nightly builds. It seems counter-intuitive to host them in a different, non-official, place.

**Comment by psftw** [comment]
To be clear, I think nightly builds are possible for official repositories.  What you are asking for with an automated build cannot be accommodated because it would remove the gatekeeper process.  It is a common paradigm to have a `namespace/project` repository for automated builds and a `project` official repository for versioned releases.
