### ISSUE TITLE
Building official Composer-bin images

### ISSUE THREAD

**Issue by Wirone** [docker-library/official-images#12866]
Recently I came up with idea to build [Composer images containing only binary](https://github.com/composer/docker/pull/250). I would like to support official library too, but after [reading FAQ](https://github.com/docker-library/faq#multi-stage-builds) and other tools' manifests I am not completely sure how to achieve that, so I came here to ask for help 🙂 

Do I understand it correctly that I should:
- add separate Dockerfiles in subdirectories (e.g. `2.3/bin/Dockerfile`)
- modify [`generate-stackbrew-library.sh`](https://github.com/composer/docker/blob/main/generate-stackbrew-library.sh) so it generates new sections in manifest, pointing proper `Tags` and `Directory`

This should work, but I have doubt about additional Dockerfile for this. Currently I use one Dockerfile with multistage build and for regular Docker Hub and Amazon ECR registries I use `--target` option during build. Is there a way to use it this way in terms of official library manifest? If not, should I build and push those images and then use them in bin Dockerfiles like:

```Dockerfile
# PoC of 2.3/bin/Dockerfile

FROM scratch
COPY --from=composer/composer:2.3 /usr/bin/composer /composer
```

So flow would be like:
- build and push community images to Docker Hub and Amazon ECR
- generate manifest and create PR to library repo
- after it gets merged, official `bin` images would be built from community images

Or maybe I should somehow point `*/bin/Dockerfile` to copy from `*/Dockerfile` (local dependency instead of using community image) 🤔?

Thanks in advance for any help.

**Comment by yosifkit** [comment]
We don't have anything in our tooling and build pipeline to build and tag specific stages of a multistage build.

For official images we try to ensure that each image is usable on its own. Usually that means that any image `FROM scratch` is either a full Linux distribution or a self-contained binary (like `busybox`). As far as I understand `composer` is that it is a PHP script, so it wouldn't be usable within a `scratch` container.

Perhaps a slimmer variant would work for the specific users?  For example, either repeating the steps of the regular image but removing the build dependencies within the layer that they are used (and some of the large, "optional" runtime dependencies like git, mercurial, and subversion) or perhaps an image `FROM php:8-alpine` with a `COPY --from composer:2.3 /usr/bin/composer /usr/bin/composer` that installs a more minimal set of runtime dependencies.

**Comment by Wirone** [comment]
> As far as I understand composer is that it is a PHP script, so it wouldn't be usable within a scratch container.

Composer is built as PHAR file (self-containing package with dependencies), but currently official images are built with whole runtime (OS+PHP+extensions) which leads to >180MB image. The idea is to create `bin` images with PHAR only, so they can be then used in other `Dockerfile`s as `COPY --from=composer:2-bin`, which will lead to downloading 2.5MB image instead of 180MB. And this is done with multistage build introduced [here](https://github.com/composer/docker/pull/250).

But I need guidance how to achieve it with manifests required for official images in this repository 🙂

**Comment by alcohol** [comment]
I think that the outcome you desire is not compatible with the philosophy / requirements for official images. A binary only image is simply not something that users can run on its own. It would merely serve as a source for user built images.

The reason that users often only want to use the binary from our official image, is because of the complexity of the runtime landscape of PHP applications. We only offer our container with the latest versions of PHP bundled with a handful of extensions relevant for Composer. Most users have tailored needs though in regards to PHP version and the extensions bundled with it.

Personally I find the discussion around "having to download a XXXmb image just for the binary" a bit tiresome as it is so heavily opinionated. There are ways to [programmatically download our binary](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md) in a semi-secure way. While this is definitely not as as elegant as `COPY --from=composer /usr/bin/composer /usr/bin/composer`, it does fit the requirement of minimal download size. It all comes down to what principles you value more dearly and what trade-offs you are willing to make.

**Comment by Wirone** [comment]
@alcohol and that's one of the reasons why I provided [PR](https://github.com/composer/docker/pull/250) _without_ support for official registry 😉 Having binary-only available in [`composer/composer`](https://hub.docker.com/r/composer/composer) would be good enough IMHO.

**Comment by tianon** [comment]
> I think that the outcome you desire is not compatible with the philosophy / requirements for official images. A binary only image is simply not something that users can run on its own. It would merely serve as a source for user built images.

This is accurate :heart:

As such, I'm going to close this now. :bow:
