### ISSUE TITLE
Question about official image `GitRepo`

### ISSUE THREAD

**Issue by Yikun** [docker-library/official-images#13057]
I am doing some investigation on official image support for Apache Spark.

Just curious that `GitRepo` should be a separate repo (`apache/spark-docker`) or using existing repo (`apache/spark`)?

Such like:

https://github.com/docker-library/official-images/blob/69305f5afe8f7658aea67c6894bfd3678059f5ee/library/solr#L8

https://github.com/docker-library/official-images/blob/6537e5494de4dea6905569048842bab5931c9bad/library/couchdb#L5

https://github.com/docker-library/official-images/blob/d7fcb735af24ccdf8c8ed02f65d12de10b6a626c/library/flink#L4

I am also try some by reference existing and have a try: https://github.com/yikun/spark-docker

But I have a question that: Why not use `apache` main repo directly? I know there might be contains many history release dockerfile and specific content structure, But I believe if we contains history dockerfile (dockerfile/path) on master branch, then we can use main repo (`apache/spark`) directly and use it hash, right?

Or there are some other considerations have to make a separate repo like `apache/spark-docker`?

**Comment by Yikun** [comment]
cc @yosifkit @tianon

**Comment by tianon** [comment]
Unfortunately having the `Dockerfile` in the root of the upstream repository (while useful for local development) doesn't work well as the target for official-images. Since the `Dockerfile` in those cases typically uses `COPY . ...`, it essentially means the entire upstream source code is now part of the Docker build context, and thus becomes part of the reviewed artifacts (see `diff-pr.sh` for how we generate our diff; it is basically taking all docker build contexts from the starting `library/foo` file and diffing them to the new contexts from the PR).

What we suggest instead is creating a separate repository to hold the "packaging", especially since you might have, for example, changes to make to the `Dockerfile` in between upstream releases of the software.

**Comment by Yikun** [comment]
> What we suggest instead is creating a separate repository to hold the "packaging", especially since you might have, for example, changes to make to the Dockerfile in between upstream releases of the software.

@tianon Sounds great! Thanks for your detail explaination!
