### ISSUE TITLE
Quesions about maven tags

### ISSUE THREAD

**Issue by ChenZhongPu** [docker-library/official-images#13717]
I am new to Docker. Recently, I found a project is using [maven:3.8-jdk-8-slim](https://hub.docker.com/layers/library/maven/3.8-jdk-8-slim/images/sha256-e0bffb105d66d613524b4ca29dcfde3a704c2d76ea388e5c2de02af232b8260c?context=explore).

My question is: why is such tag `3.8-jdk-8-slim` not listed in either [Docker hub](https://hub.docker.com/_/maven) or [Github](https://github.com/docker-library/official-images/blob/master/library/maven)? How can I find its Dockerfile?

**Comment by tianon** [comment]
I wish we had better ways to make it more clear, but from the official images program we don't have much more than any other image publishers for customizing Hub -- what you're experiencing is that the tag you're using isn't listed on https://hub.docker.com/_/maven because it isn't supported any more (but was at some point in the past; in this specific case, it's been unsupported since September 2022 in 22b7e3d14cfffc0f9f45dcee300e74244e3f2b88).

The last `Dockerfile` it was built from was https://github.com/carlossg/docker-maven/blob/ac292f26884bf2be9fe69f6e397da3b124c1e35c/openjdk-8-slim/Dockerfile, and the reason it was removed is because the base image it's `FROM` is _also_ no longer supported (`openjdk:8-jdk-slim`).  The most popular alternative is probably going to be the variants based on Eclipse Temurin, but which one is "suitable" is going to vary based on your experience, needs, use case, etc.
