### ISSUE TITLE
[mysql] Access denied to mysql server immediately after container was restarted.

### ISSUE THREAD

**Issue by jottr** [docker-library/official-images#1378]
Let's create a basic mysql instance:
`$ docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=root -p 3306:3306 -d mysql`

and restore a dump: 

`$ mysql -h $(docker-machine ip dev) -u root -proot -P 3306 < dump.sql`

and connect to the instance serving the dump:

```
$ mysql -h $(docker-machine ip dev) -u root -proot -P 3306
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 4
Server version: 5.7.10 MySQL Community Server (GPL)
.....
mysql> 
```
Let's stop the container, and immediately restart it:

````
$ docker stop some-mysql && docker start some-mysql
```

and now, connect again:

```
$ mysql -h $(docker-machine ip dev) -u root -proot -P 3306
ERROR 1045 (28000): Access denied for user 'root'@'192.168.99.1' (using password: YES)
```

**Comment by yosifkit** [comment]
Did your dump include the users and passwords from the old database?

**Comment by jottr** [comment]
Yes. I did a complete dump.

**Comment by yosifkit** [comment]
That would probably do it; I would assume that the import did not have a `FLUSH PRIVILEGES`, so that a connect before restart would work but would fail after restart.  I would recommend just deleting the `mysql.users` table from the import so that it doesn't affect your dockerized database.  Unless you want those users but then you will have to connect as one of them and they might not be accessible from any host.

**Comment by jottr** [comment]
Ok. I just created another dump without the mysql specific databases. 
That fixed my problem. Thank you for helping out.

**Comment by franklyu** [comment]
How do you solve ？
