### ISSUE TITLE
Remove existing tags of official images

### ISSUE THREAD

**Issue by carminevassallo** [docker-library/official-images#13858]
Dear team,

We would need to remove an existing tag based on a new policy about our docker-image versioning. However, based on the available docs, this does not seem to be possible. Keeping such tag might generate confusion among our users. 

Is it possible to remove an existing tag from an official image on dockerhub? If yes, what's the process for it? Shall we document it on the `README.md` of this repo?

p.s.
we own the sonarqube images, but this topic might interest other maintainers as well.

**Comment by tianon** [comment]
We don't typically remove tags because it's very disruptive to existing users when we do so (with very few ways to communicate to users what's happened or what they can/should do about it), but we are willing to do so on a case-by-case basis per maintainer request (and have done so several times in the past).

Here's a semi-related blurb we often use when discussing removing tags from the `library/XXX` files:

> Removing tags here will remove them from the "Supported" section on the Hub readme (and will prevent us from spending cycles rebuilding them on the official build servers), but the tags will still be available to users who want them.  (See https://github.com/docker-library/official-images#library-definition-files for more detail on this.)

**Comment by carminevassallo** [comment]
@tianon, thanks for your input. It's very good to know that this is something we can ask in exceptional cases. However, we re-evaluated our initial plan and we won't ask to remove the tag immediately.
