### ISSUE TITLE
`r-base` is not updated (Not built regularly)

### ISSUE THREAD

**Issue by eitsupi** [docker-library/official-images#14191]
(Original posted rocker-org/rocker#517)

I looked at DockerHub and noticed that r-base had not been updated and was showing a large number of vulnerabilities.
I thought that updates to the base image (`debian:testing`) automatically triggered updates to `r-base`, but I guess that is not the case now?

I have looked at other Docker Official Images and most of them seem to be updated frequently.
https://hub.docker.com/search?image_filter=official&q=&sort=updated_at&order=desc

https://hub.docker.com/_/r-base/tags
![image](https://user-images.githubusercontent.com/50911393/222428609-e93d98f7-bc6d-46bc-80b8-78ac467495e8.png)
![image](https://user-images.githubusercontent.com/50911393/222428903-4fc545fe-228c-41a9-9fc2-3db87080b9a7.png)

What is the difference between an image that is built periodically and one that is not?
Is it possible to change r-base to build periodically?

Let me know if this is not the appropriate place to submit this issue, Thanks.

**Comment by yosifkit** [comment]
First, `debian:testing` is not a security supported release of Debian; any security fixes appearing there are just from regular package bumps (not usually backports from the security team like the stable releases), so the `testing` packages usually lag behind security fixes available in `bullseye` (`stable`) and `buster` (`oldstable`) releases.

Second, it does get our roughly monthly rebuilds when we rebuild all `debian` images and then trigger dependent official images. It has failed to build at any of the rebuilds: https://doi-janky.infosiftr.net/job/multiarch/view/images/view/r-base/job/amd64/job/r-base/. (I triggered them again because jenkins has helpfully pruned old build logs).

**Comment by tianon** [comment]
cc @cboettig @eddelbuettel (probably worth either installing `adduser` or maybe even better switching to `useradd`?)

**Comment by eddelbuettel** [comment]
> cc @cboettig @eddelbuettel (probably worth either installing adduser or maybe even better switching to useradd?)

I am confused.  These days, with Docker refusing to build off GH, I build each and every image here first.  They do not fail.  So I must be missing _something_ (or it is simply a change more recent than the R 4.2.2 update in which case I will get to it by March 15 when R 4.2.3 is released).

**Comment by eddelbuettel** [comment]
@yosifkit If it breaks, and if it is my code, an issue ticket is _always_ appreciated.

**Comment by tianon** [comment]
Unfortunately, we don't have anything set up to catch and notify based on build failures -- we do try to review them periodically and reach out to the relevant maintainer, but it doesn't currently happen as often as we'd like it to.

What we do for our own repositories is have a set of GitHub Actions that do "smoke test" builds (and run the tests from this repository on the resulting images), and we run that on every commit and on a schedule every week too, which helps us catch high-level cases like this one. :bow:

For what it's worth, here's the current build failure for `r-base:latest`:

```console
$ docker build --pull r-base/4.2.2
Sending build context to Docker daemon   5.12kB
Step 1/11 : FROM debian:testing
testing: Pulling from library/debian
bbf0dc8a79b5: Pull complete 
Digest: sha256:1b3e3069eec316f51dcf50d4fe03e5366872c9c4842f2b63e8b293473efca148
Status: Downloaded newer image for debian:testing
 ---> e58dd4584cb9
Step 2/11 : LABEL org.opencontainers.image.licenses="GPL-2.0-or-later"       org.opencontainers.image.source="https://github.com/rocker-org/rocker"       org.opencontainers.image.vendor="Rocker Project"       org.opencontainers.image.authors="Dirk Eddelbuettel <edd@debian.org>"
 ---> Running in bda872fb8649
Removing intermediate container bda872fb8649
 ---> 6041f28da768
Step 3/11 : RUN useradd docker 	&& mkdir /home/docker 	&& chown docker:docker /home/docker 	&& adduser docker staff
 ---> Running in 7dd4b921fcbd
/bin/sh: 1: adduser: not found
The command '/bin/sh -c useradd docker 	&& mkdir /home/docker 	&& chown docker:docker /home/docker 	&& adduser docker staff' returned a non-zero code: 127
```

**Comment by eddelbuettel** [comment]
Thanks -- noted on the lack of catching the errors.  

As @eitsupi and I came to realized we too should auto build this so that I catch this.  The `adduser` fail does ring a bell, I am sure I have seen this somewhere else not that long ago. Maybe something dropped off the base image.

Anyway, R 4.2.3 is around the corner.  We'll be all clean and shiny by then, and will look into weeklies for our variant (i.e. rocker/r-base) as well.

**Comment by eitsupi** [comment]
Thanks everyone for the detailed replies!
I understood that the build had failed.

It would be really great if these build situations were easier to find. (I really have no idea until now what infrastructure these are built on)
