### ISSUE TITLE
arm64v8 and other non-standard architecture images don't show as "official images"

### ISSUE THREAD

**Issue by AliceGrey** [docker-library/official-images#15249]
None of the images under https://hub.docker.com/u/arm64v8/ show as official images.

**Comment by yosifkit** [comment]
🤔This applies to every architecture namespace we use, even the most common [amd64](https://hub.docker.com/u/amd64/). They've mostly been an implementation detail for where we stage architecture specific images before they are "promoted" to `library/`. Because not all architectures build equally fast, they can finish at their own pace and be added to the image index in `library/` when they are ready without slowing down the others. Container registries don't have locking or atomic updates, so we can't just have each arch update the image index directly.

Even though you can specify `--platform` with Docker and Containerd tooling, the architecture specific images are useful to be able to pull that specific architecture or fail and not have docker/containerd fallback to alternative architecures.

It might cause confusion if, for example, there are suddenly many `Alpine` official images labeled on Docker Hub. Sure, all the sha256 image ids are the same, but that takes digging to see that.

I'll pass this issue along to product folks and let them decide if Docker Hub should do something special to our DOI architecture-specific repos: 

-	ARMv6 32-bit (`arm32v6`): https://hub.docker.com/u/arm32v6/
-	ARMv7 32-bit (`arm32v7`): https://hub.docker.com/u/arm32v7/
-	ARMv8 64-bit (`arm64v8`): https://hub.docker.com/u/arm64v8/
-	Linux x86-64 (`amd64`): https://hub.docker.com/u/amd64/
-	Windows x86-64 (`windows-amd64`): https://hub.docker.com/u/winamd64/
-	ARMv5 32-bit (`arm32v5`): https://hub.docker.com/u/arm32v5/
-	IBM POWER8 (`ppc64le`): https://hub.docker.com/u/ppc64le/
-	IBM z Systems (`s390x`): https://hub.docker.com/u/s390x/
-	MIPS64 LE (`mips64le`): https://hub.docker.com/u/mips64le/
-	RISC-V 64-bit (`riscv64`): https://hub.docker.com/u/riscv64/
-	x86/i686 (`i386`): https://hub.docker.com/u/i386/
