### ISSUE TITLE
centos/httpd out of date and vulnverable

### ISSUE THREAD

**Issue by macropin** [docker-library/official-images#1539]
There have been no new builds of [centos/httpd](https://hub.docker.com/r/centos/httpd/builds/) for 4 months. This image will be vulnerable to all the latest SSL / glibc issues #1448 and #1490.

Builds appear to be failing due to outdated docker / kernel in use at the docker hub. See 
- https://github.com/docker/docker/issues/6980 
- https://github.com/CentOS/CentOS-Dockerfiles/issues/46

**Comment by psftw** [comment]
The `centos` image on DockerHub is part of the Official Repositories program, whereas the derivative `centos/*` images are not.  Since Official Repositories are built outside of DockerHub, they are not affected.  The automated build problems with `set_cap_file` are known and will be addressed (https://github.com/docker/hub-feedback/issues/461#issuecomment-178027580).
