### ISSUE TITLE
monica:latest not rebuilt?

### ISSUE THREAD

**Issue by TimWolla** [docker-library/official-images#15404]
It appears that for some reason the monica:latest tag was not rebuilt, despite the base image changing:

https://hub.docker.com/_/monica/tags / https://hub.docker.com/layers/library/monica/latest/images/sha256-9e4270cde2bbb51b07dafa3f8df6ddc9f7fdb2507fc03a993deddd12f5b20737?context=explore

latest was last updated 3 months ago, however the `php:8.1-apache` base image was last rebuilt a few hours ago:

https://hub.docker.com/layers/library/php/8.1-apache/images/sha256-e4912ed6c18ad4f7fbcd39d7c20b73f7e6e3215176882bde6ae492278f8ef3b9?context=explore

**Comment by yosifkit** [comment]
The build queue is still very full (https://doi-janky.infosiftr.net/) since all Debian images have been working though rebuilds since https://github.com/docker-library/official-images/pull/15395 was merged.

But it does look like the Debian-based versions of `monica` have been failing to build for a while (https://doi-janky.infosiftr.net/job/multiarch/view/images/view/monica/) and the error seems very familiar:

```console
checking for libmemcached location... configure: error: memcached support requires libmemcached. Use --with-libmemcached-dir=<DIR> to specify the prefix where libmemcached headers and library are located
ERROR: `/tmp/pear/temp/memcached/configure --with-php-config=/usr/local/bin/php-config --with-libmemcached-dir=no --with-zlib-dir=no --with-system-fastlz=no --enable-memcached-igbinary=no --enable-memcached-msgpack=no --enable-memcached-json=no --enable-memcached-protocol=no --enable-memcached-sasl=yes --enable-memcached-session=yes' failed
```

Aha! found it: https://github.com/docker-library/php/issues/1418; So, the `monica` Dockerfiles need to add `libssl-dev` to the `apt-get install` of dev dependencies (or switch to the bullseye-based PHP images).

**Comment by TimWolla** [comment]
Thanks, filed upstream in monicahq/docker#133

**Comment by asbiin** [comment]
Hi! I've updated the image recently, and the build is fine without adding `libssl-dev` now. Maybe a side effect?
