### ISSUE TITLE
No updates of mariadb images on Docker Hub Repository

### ISSUE THREAD

**Issue by Delor3an91** [docker-library/official-images#16175]
Hi,

The last `mariadb:latest` images is from **23th November 2023**...

On the Docker Hub Repository mariadb page :
[https://hub.docker.com/_/mariadb/tags](url)

It's write that the tag latest was updated **14 days ago** from now, **1st February 2024**.

It's write that **several vulnerabilities** have been patched so it's a **real problem** that `mariadb` docker images are so old and not updated since.

May You please take a look and refresh all of them?

Wish You well

**Comment by LaurentGoderre** [comment]
This will trigger a rebuild of the image: https://github.com/docker-library/official-images/pull/16169

**Comment by Delor3an91** [comment]
> This will trigger a rebuild of the image: https://github.com/docker-library/official-images/pull/16169

@LaurentGoderre ,

Does it mean that this problem is resolved?


Wish You well

**Comment by yosifkit** [comment]
This might be similar to: https://github.com/nginxinc/docker-nginx/issues/863#issuecomment-1922528843 (TL;DR some of the images now use `SOURCE_DATE_EPOCH` during build, so they look older than they actually are)

For example, `mariadb:latest` (https://explore.ggcr.dev/?image=mariadb%3Alatest) should soon have the `org.opencontainers.image.created` annotations once the rebuild caused by the Ubuntu update is pushed out.

---

The `git` history of https://github.com/docker-library/repo-info/tree/master/repos/mariadb can also be useful to see what changes between image pushes.

**Comment by Delor3an91** [comment]
Hi @yosifkit ,

Thank You for that information. Do You know when MariaDB docker images' will be updated? Cause I do care about the security flaws.

Wish You well

**Comment by yosifkit** [comment]
The `mariadb` images were just rebuilt about three days ago. The non-amd64 architectures have been delayed by some build server issues but should be pushed out today.

https://explore.ggcr.dev/?image=mariadb%3Alatest: 
```json
"org.opencontainers.image.created": "2024-02-02T00:54:44Z",
```

**Comment by Delor3an91** [comment]
Hi @yosifkit ,

I'm concerned about the ARM Docker images.

Take You in the loop.

Wish You well

**Comment by tianon** [comment]
Ok, ARM is up now -- s390x is still in progress (our worker is definitely struggling :sob:), but I think that's probably good enough for considering this resolved. :+1:

**Comment by Delor3an91** [comment]
Hi @yosifkit ,

I confirm images are now updated.

Wish You well
