### ISSUE TITLE
More RISC-V builds - how can I help?

### ISSUE THREAD

**Issue by IngwiePhoenix** [docker-library/official-images#16302]
Hello there!

I have a stable VisionFive2 on a 6.6.0 kernel and I want to use it for something good - and since most common image tags, such as `alpine:3.19` and the likes - do not exist, I would like to know how I can help to improve that situation. Compute is costly, thus build servers cost a lot; I know that... so, I would love to help, if possible.

1. What is the process of joining, partaking or sharing RISC-V images to be added to the standart library?
2. Where do I find the raw Dockerfiles that I can then use to build the images - or is there some CI/CD script that can run in, let's say Jenkins, that I could utilize by just spinning up a Jenkins instance?

Thank you and kind regards,
Ingwie

**Comment by tianon** [comment]
As you've noted `alpine:3.19` and friends don't include `riscv64` which is a bit complicated, and not something we can fix in the Docker Official Images directly (and without fixing that, most images won't have support since they're understandably based on stable releases of their upstream distributions).

I know in Debian there's been some great progress towards this (`riscv64` is an official archive architecture now and _might_ be included in Debian Trixie if they can get through the transition work they're undergoing in time).  I think the `#debian-riscv` IRC channel on OFTC is the most active place where that gets discussed, although https://lists.debian.org/debian-riscv/ is also used for linking riscv-related bugs to.

I believe https://gitlab.alpinelinux.org/alpine/aports/-/issues/13269 is still the best place to track the efforts within the Alpine community.

(I'm going to go ahead and close this since there's not really anything we'll do about this here, but feel free to continue discussing.)

**Comment by gdams** [comment]
@tianon is there any hope of an ubuntu base image for RISC-V at some point?

**Comment by whalelines** [comment]
I would imagine that would be in Canonical's plans since they are supporting RISC-V now, but you would have to check with Canonical for a definitive answer.

https://github.com/docker-library/official-images/blob/master/library/ubuntu

**Comment by tianon** [comment]
Yes, definitely -- they had it previously, and they do plan to bring it back, but I think they've had some challenges in their infrastructure/build process that made that complicated.  They definitely still are planning to do so.

**Comment by gdams** [comment]
> Yes, definitely -- they had it previously, and they do plan to bring it back, but I think they've had some challenges in their infrastructure/build process that made that complicated. They definitely still are planning to do so.

Thanks @tianon, I did see that there were some old builds floating around so figured it may be in the pipeline again. To give some context the eclipse-temurin project has published their first RISC-V binary so we're looking to add support to our images. Right now the only option seems to be Debian sid so having a supported distro would be great!
