### ISSUE TITLE
HHVM/HHVM as official

### ISSUE THREAD

**Issue by Webysther** [docker-library/official-images#1638]
The repository is official of facebook team: https://hub.docker.com/r/hhvm/hhvm/

https://twitter.com/HipHopVM/status/705063018606886912

**Comment by yosifkit** [comment]
They would need to submit it for consideration to the official images. There was a user-supplied HHVM that was rejected (https://github.com/docker-library/official-images/pull/1043) because upstream wanted to create one (https://github.com/hhvm/packaging/issues/138).  We would welcome a PR from them.

As a side note, their Dockerfiles seem pretty sane and we would only have slight recommmendations: https://github.com/hhvm/hhvm-docker/blob/master/hhvm-latest/Dockerfile.
