### ISSUE TITLE
Add LoongArch architecture support

### ISSUE THREAD

**Issue by zhaixiaojuan** [docker-library/official-images#16404]
The LoongArch architecture (LoongArch) is an Instruction Set Architecture (ISA) that has a RISC style.

Documentations:
ISA:
https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html
ABI:
https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-EN.html
More docs can be found at:
https://loongson.github.io/LoongArch-Documentation/README-EN.html

The alpine community is currently adding support for the LoongArch architecture, and the community has already merged some patches. According to the current progress, the alpine upstream community should soon support the LoongArch architecture.
After the alpine upstream community supports the LoongArch architecture, can the Docker official image consider adding a LoongArch architecture image? If you need machine or other help, we will fully support you.

Key PR merged by alpine community:
https://gitlab.alpinelinux.org/alpine/tsc/-/issues/72
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/61611
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/61612

**Comment by whalelines** [comment]
Thank you for the request to add support for LoongArch to DOI, @zhaixiaojuan! We really appreciate your interest in DOI.

Unfortunately at this time we have no plans to add support for LoongArch. We will reevaluate this decision as the situation evolves.

Thanks again and take care!

**Comment by zhaixiaojuan** [comment]
@tianon @whalelines 
Thank you very much for your reply. Currently, go, gcc, kernel, llvm and other upstreams already support the loongarch architecture, and alpine and debian systems are also integrating patches for the loongarch architecture.

I very much hope that the official image can also support the loongarch architecture. But at the moment I don't know exactly what needs to be done to achieve this goal. I hope to get some specific evaluation indicators. I will prepare in advance based on these indicators and strive to achieve this goal as soon as possible. Can you help us?

Thank you very much and look forward to your reply and guidance.

**Comment by whalelines** [comment]
You have noted some metrics we track but there are other internal metrics as well as support and compliance considerations. As such, we cannot communicate a checklist of prerequisites. Ultimately, supporting additional architectures for DOI requires a significant investment from Docker and while we appreciate your interest and enthusiasm, at this time we cannot justify taking on an additional architecture. As mentioned previously, we will continue to monitor the situation.

**Comment by zhaixiaojuan** [comment]
Thank you very much for your reply

**Comment by huajingyun01** [comment]
Hi @tianon  @whalelines

Sorry to bother you, we have been working on the  [Alpine Linux loongarch64 port](https://gitlab.alpinelinux.org/alpine/tsc/-/issues/72) and will continue to work hard on it.

The following is just an update on the progress of Alpine Linux loongarch64:
1. With the help and support of @ncopa and many developers/maintainers, the upstream has successfully onlined  loongarch64 [CI/builder ](https://build.alpinelinux.org/) in the past two months, and it is running stably.
2. The packages built by the builder are uploaded to [dev.a.o](https://dev.alpinelinux.org/edge/). I believe the loongarch64 packages are finally being made available on [dl-cdn.a.o](https://dl-cdn.alpinelinux.org/alpine/), instead of just [dev.a.o](https://dev.alpinelinux.org/edge/)
4. Alpine's TSC team also plans to [add loongarch64 in the next release v3.21](https://gitlab.alpinelinux.org/alpine/tsc/-/blob/master/minutes/2024-07-02.md?ref_type=heads) (probably November or earlier),I really appreciate it

Additionally, we have created a working [Alpine ISO](https://dev.alpinelinux.org/~loongarch/edge/releases/loongarch64/), and I have actually been working on a physical machine with Alpine Linux loongarch64, and so far everything has been working fine.

Docker images are an indispensable part of Alpine users and Alpine Linux, and I would appreciate it if you could take the time to reconsider adding support for LoongArch to DOI.

Since it is been a while since last comments, I would like to update you on recent progress on Alpine Loongarch64 upstream and would love to hear your suggestions. 

Thanks again!

**Comment by huajingyun01** [comment]
> Thank you for the update. No changes on our end. We will continue to assess.

Hi @whalelines  Thank you very much！
I will continue to look forward to it.  If you have any questions, I am always here.

**Comment by ncopa** [comment]
This seems to block the latest alpine edge image: https://github.com/docker-library/official-images/issues/16404

**Comment by tianon** [comment]
Sorry, but as noted above, we don't currently support loong(arch)64, and it is not currently on our roadmap to do so.
