### ISSUE TITLE
Official Chiselled Ubuntu images support?

### ISSUE THREAD

**Issue by gdams** [docker-library/official-images#16887]
Is there a plan to support a distroless chiselled base image? It would be great to have one!

See https://ubuntu.com/engage/chiselled-ubuntu-images-for-containers

**Comment by whalelines** [comment]
What do you mean by support for chiseled base imaged? A chiseled image cannot typically serve as a base image for other images since it does not have the tooling to add other software. Nor would a chiseled OS image be very useful to use as is. "Chiseling" an image is more of a process, a method for creating images, than a image in an of itself.

**Comment by gdams** [comment]
I guess what I'm trying to ask is would official images be able to create a distroless official image using the Ubuntu Chiselled tooling

**Comment by gdams** [comment]
For example, the .NET team publish a [base image](https://github.com/dotnet/dotnet-docker/blob/main/src/runtime-deps/8.0/jammy-chiseled/amd64/Dockerfile) which they then base their [runtime image](https://github.com/dotnet/dotnet-docker/blob/main/src/runtime/8.0/jammy-chiseled/amd64/Dockerfile) from.

**Comment by whalelines** [comment]
The current DOI build system supports Dockerfile and OCI artifacts as input. We do not currently have any plans to support alternative build mechanisms. You can peruse [Docker's public roadmap](https://github.com/docker/roadmap?tab=readme-ov-file) if you wish to request features like this. Thanks for your interest in DOI!
