### ISSUE TITLE
node-10 security issues

### ISSUE THREAD

**Issue by pierreozoux** [docker-library/official-images#1764]
Hi!

it looks like [node-10](https://hub.docker.com/r/library/node/tags/0.10/) is vulnerable to a lot of issues. I know it is deprecated, but still, meteor is based on that.
Is there a way to update it?

Thanks!

**Comment by yosifkit** [comment]
`node:0.10` is still in the supported list, so it will get rebuilt when https://github.com/docker-library/official-images/pull/1767 is merged (but probably will take a few days since there are many images to build).  I am not sure if all of the CVEs listed there are fixed in Debian's apt repos, so some CVEs may linger after the update.

**Comment by Moghedrin** [comment]
Cleaning house on old issues: node:0.10 is no longer supported, and further issues should be filed against node upstream.
