### ISSUE TITLE
Running Docker container on port 80

### ISSUE THREAD

**Issue by joanlopez** [docker-library/official-images#1788]
Hi,

I have an instance of the latest version with Apache. Everything was working well until now, when I want to change the exposed port (8080 to 80) to deploy to "production".

I've followed the next steps:

> docker commit
> docker stop
> docker rm
> docker run -p 80:80

(summary of the steps)

The Docker container is working well, but I can't visit the site. The problem is that when I try to load the website: my-ip:80. It redirects me automatically to :8080. Of course, it doesn't work, because now my Docker container is exposed on the port 80.

There is any configuration or setting that I have to change to make this change (8080->80) possible?

I think that with something that avoids this port automatically redirect will be enough.

Many thanks ;)

**Comment by yosifkit** [comment]
That sounds like you are using WordPress; which uses whatever URL you access it with as its URL "forever" (and hardcodes it throughout the database).  They have some info on [changing the site URL](https://codex.wordpress.org/Changing_The_Site_URL); `wp-cli` mentioned at the bottom seems the most comprehensive.

I'm curious that `docker commit` worked since all changeable files like themes and uploads are in a `VOLUME` and would not get committed to the resulting image.  You'll need to use `-v /host/storage/:/var/www/html/` and then send that folder to whichever host will be running your WordPress (or just run the same `-v` on a new container with the new port).
