### ISSUE TITLE
Request to rebuild several images due to expired Corretto PGP Key

### ISSUE THREAD

**Issue by benty-amzn** [docker-library/official-images#18021]
Hello,

We're reaching out from the Amazon Corretto team to request that several images in the Official Library be rebuilt.
The Amazon Corretto [PGP Key expired](https://github.com/corretto/corretto-17/issues/205) on 2024-12-03.
While the key has since been extended, the issue has continued to result in availability issues for customers running `apt update` in container images which were built with the now-expired key.
We know that at least the [`maven:*-amazoncorretto-*-debian` images are impacted](https://github.com/carlossg/docker-maven/issues/519).
Based on a keyword search for `corretto` in this repository, we suspect that the following images may also experience impact:

- library/gradle
- library/jetty
- library/maven
- library/tomcat

Would it be possible to rebuild these images proactively to help purge the expired key?

**Comment by yosifkit** [comment]
Unfortunately, the Docker Official Images build system does not currently support rebuilds outside of Dockerfile and base image updates. It is a very manual process to reset the things for an image or set of images.

>Tags in the [official-images] library file[s] are only built through an update to that library file or as a result of its base image being updated (ie, an image `FROM debian:bookworm` would be rebuilt when an updated `debian:bookworm` is built). 
>
>\-https://github.com/docker-library/official-images/tree/2f086314307c04e1de77f0a515f20671e60d40bb#library-definition-files

From what I can tell, `amazoncorretto` and the images from it in `gradle`, `jetty`, and `tomcat` are unaffected because `yum` doesn't check the gpg key's expiration.

For the 5 `maven` images from Debian with Corretto installed in the Dockerfile, the fastest fix would be to embed and check a checksum (sha256, sha512, etc) of the `corretto.key` in the Dockerfile just after downloading it to create a natural cache bust for the image.

https://github.com/carlossg/docker-maven/blob/8cfe24baffa5b250f7bb2d31ce233fc28f3c4f20/amazoncorretto-17-debian/Dockerfile#L10

Something roughly like this:
```Dockerfile
  && curl -fL https://apt.corretto.aws/corretto.key -o corretto.key \
  && echo '[insert sha256sum] *corretto.key' | sha256sum -c - \
  && gpg --batch --import corretto.key \
  && rm corretto.key \
  && gpg --batch --export '6DC3636DAE534049C8B94623A122542AB04F24E3' > /usr/share/keyrings/corretto.gpg \
```

**Comment by carlossg** [comment]
maven should be fixed with https://github.com/docker-library/official-images/pull/18037
