### ISSUE TITLE
Add entrypoint for httpd image and accept additional arguments to httpd process

### ISSUE THREAD

**Issue by kinghuang** [docker-library/official-images#1912]
Can the httpd official image be modified to specify an entrypoint that accepts extra arguments to httpd? Right now, it uses a cmd to httpd-foreground than then execs httpd, making it impossible to pass extra arguments without making a custom image.

**Comment by yosifkit** [comment]
We had not seen the need for it yet.  You can currently just `docker run httpd httpd -DFOREGROUND -more -args` and the only thing lost is the auto-removal of the pid on start of the `httpd-foreground` script.

**Comment by kinghuang** [comment]
Ah, I hadn't considered just specifying httpd (the executable) and its arguments directly because of the existence of the custom script. I can work with that.

At the same time, I feel like it's not an obvious way to use the image, since it requires digging into the source repo, examining httpd-foreground, and repeating its arguments plus custom ones. Perhaps more documentation would help.

**Comment by Moghedrin** [comment]
Closing this issue, because it looks like this specific issue was solved! \o/ That being said, documentation for the repos are generated from the [documentation repo](https://github.com/docker-library/docs), and welcome pull requests to improve them if you find some specific examples underrepresented. :)
