### ISSUE TITLE
easy_install / setuptools is v20.10.1 instead of v25.1.0

### ISSUE THREAD

**Issue by cclauss** [docker-library/official-images#1986]
```
# easy_install --version
setuptools 20.10.1 from /usr/local/lib/python3.5/site-packages (Python 3.5)
# pip install --upgrade setuptools
Collecting setuptools
  Downloading setuptools-25.1.0-py2.py3-none-any.whl (442kB)
    100% |████████████████████████████████| 450kB 2.0MB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 20.10.1
    Uninstalling setuptools-20.10.1:
      Successfully uninstalled setuptools-20.10.1
Successfully installed setuptools-25.1.0
# easy_install --version
setuptools 25.1.0 from /usr/local/lib/python3.5/site-packages (Python 3.5)
```

**Comment by yosifkit** [comment]
We don't install a specific version of `easy_install`, we just use whatever is bundled with python. Should we be tracking and updating its version like we do with [`pip`](https://github.com/docker-library/python/blob/4b37165e4a4bd7af2b54ffc690fa744e60d9a01b/3.5/Dockerfile#L62)?

Next time, this should be reported on the [python repo](https://github.com/docker-library/python/issues) rather than the general official images repo.

**Comment by tianon** [comment]
After https://github.com/docker-library/python/pull/194, `setuptools` should now be more up-to-date than it was before. :+1:
