### ISSUE TITLE
Wheel is not included in Python 3

### ISSUE THREAD

**Issue by r-darwish** [docker-library/official-images#2016]
The wheel package is included in Python 2 but is not in Python 3:

```
docker run --rm python:2 bash -c "pip list | grep wheel"
wheel (0.29.0)

docker run --rm python bash -c "pip list | grep wheel"
```
This results in pip not building wheels in Python 3, while it does build them in Python 2.

**Comment by yosifkit** [comment]
It looks like we get `wheel` in python 2 images because we are [using `get-pip.py`](https://github.com/docker-library/python/blob/19bca6a2b300444b00d7d64ef4104539a521cdc2/2.7/Dockerfile#L57) whereas the python 3 images rely on pip being bundled with python.  Maybe we should just use `get-pip.py` in both cases?

**Comment by r-darwish** [comment]
Opened in docker-library/python
