### ISSUE TITLE
Docker image for elasticsearch 2.4

### ISSUE THREAD

**Issue by ardakara** [docker-library/official-images#2058]
What would be the best way to get a docker image for the not-yet-released 2.4 branch of elasticsearch? (https://github.com/elastic/elasticsearch/tree/2.4)

The branch has a change (https://github.com/elastic/elasticsearch/pull/19933) we'd like to try out on our stack, changing as close to nothing else from the official 2.3 image as possible. 

Thanks!

**Comment by Moghedrin** [comment]
Because we try as much as possible to remain instep with upstream's official releases, elasticsearch 2.4 will only become an official image when it is an official release. That being said, there is absolutely nothing stopping you from building your own image via a [Dockerfile](https://docs.docker.com/engine/reference/builder/) :)

**Comment by tianon** [comment]
Slightly more color @yosifkit shared privately:

> We already have the newest elasticsearch release with the `5.0` alpha series.  Since we use their apt repository, I would think we would have to wait for another release.  If you want to test from master, then you'd have to make a container that has Gradle and then build from the elasticsearch git repo (https://github.com/elastic/elasticsearch#building-from-source).
