### ISSUE TITLE
nginx:alpine doesn't receive SIGHUP

### ISSUE THREAD

**Issue by EvgenyOrekhov** [docker-library/official-images#2189]
Sending SIGHUP to nginx process is supposed to reload nginx configuration, but `docker kill -s SIGHUP nginx` doesn't work.

**Comment by yosifkit** [comment]
This might be better handled in https://github.com/nginxinc/docker-nginx/issues, since the maintainers may not be actively watching this repo.

Have you checked with `docker exec -it nginx cat /path/to/config` that the container sees the new file?  Did you mount your config directory or just a file with `-v` on the `docker run`?  If it was a single file, the bind mount is by inode and not filename, so if you edited with vim or sed on your host, then a new file was created that is not the same as the one reference by the running container.

**Comment by EvgenyOrekhov** [comment]
@yosifkit thanks, looks like it is indeed a problem with inodes. I mounted a file and then `git pull` on the host created a new inode, which the container can't see.

Would mounting a directory solve the issue? Or does `git pull` always create new inodes for directories too?

**Comment by yosifkit** [comment]
Mounting a directory should work.

**Comment by EvgenyOrekhov** [comment]
Directories are mounted using inodes too, so recreating the mounted directory will also break the mount point.

Closing as the issue is not with the nginx:alpine image.
