### ISSUE TITLE
centos: no write permission on some folders of /usr/

### ISSUE THREAD

**Issue by flx42** [docker-library/official-images#2295]
```
$ docker run -ti centos:7
[root@22c9f85711f3 /]# ls -la /usr
total 72
drwxr-xr-x 13 root root  4096 Sep  6 13:59 .
drwxr-xr-x  1 root root  4096 Oct 31 18:26 ..
dr-xr-xr-x  2 root root 12288 Sep  6 14:02 bin
drwxr-xr-x  2 root root  4096 Aug 12  2015 etc
drwxr-xr-x  2 root root  4096 Aug 12  2015 games
drwxr-xr-x  3 root root  4096 Sep  6 14:00 include
dr-xr-xr-x 19 root root  4096 Sep  6 14:02 lib
dr-xr-xr-x 26 root root 16384 Sep  6 14:02 lib64
drwxr-xr-x  7 root root  4096 Sep  6 14:02 libexec
drwxr-xr-x 12 root root  4096 Sep  6 13:59 local
dr-xr-xr-x  2 root root  4096 Sep  6 14:02 sbin
drwxr-xr-x 52 root root  4096 Sep  6 14:02 share
drwxr-xr-x  4 root root  4096 Sep  6 13:59 src
```
Some folders are only "r-x" for owner. It's totally fine when you're root, because root doesn't care, but it creates some headaches when exporting the filesystem somewhere:
```
$ docker export d773bc2f30eb | tar -xvf - -C /tmp/centos7
[...]
$ touch /tmp/centos7/usr/src/foo # OK
$ touch /tmp/centos7/usr/lib/bar
touch: cannot touch '/tmp/centos7/usr/lib/bar': Permission denied
```

Is this by design? debian and ubuntu images are `rwx` for all these folders.

**Comment by yosifkit** [comment]
The CentOS image maintainers don't necessarily watch this repo, since this repo pertains more to the building of all official images.  You should probably open an issue on the centos bug tracker or in [their repo](https://github.com/CentOS/sig-cloud-instance-images/issues) ([source](https://github.com/docker-library/docs/tree/938142dcc9d91e71698541185e104de97f937e11/centos#issues)).

**Comment by flx42** [comment]
@yosifkit thanks, closing this bug then.
