### ISSUE TITLE
No tag for latest ubuntu stable / non LTS

### ISSUE THREAD

**Issue by NoahO** [docker-library/official-images#2323]
Hi, 

Can we have a tag for the latest ubuntu release that is not an LTS? 

Currently yakkety is tagged with dev, despite being a stable release, and there is no tag that follows the latest release, only the latest LTS. 

Could we have something like ubuntu: stable as a tag? And maybe ubuntu: lts to make things clearer. 

Cheers!

**Comment by OddBloke** [comment]
Provided `docker pull ubuntu` and `docker pull ubuntu:latest` continue to point at the most recent LTS (which is where we want people to land if they don't specifically ask otherwise), having a separate tag seems like a good idea.

With regards, specifically, to calling it `stable`, the version of Ubuntu you get with `ubuntu:stable` won't actually be stable over time, it'll change every 6 months. I'm worried that people might opt for the `stable` tag expecting it to be, effectively, LTS (nginx:stable, for example, is an _older_ version that nginx:latest, so this wouldn't be a wildly unreasonable thing for them to do). These people will get a nasty surprise within a few months of deploying their system.

If `latest` wasn't what people would plump for when they don't know any better (when we would like them to end up with an LTS), that would seem more apropos. Perhaps `released` or `releases`? Other ideas more than welcome.

(This new tag should obviously also point at the latest LTS when that's the most recent release.)

**Comment by OddBloke** [comment]
Perhaps `rolling`?

**Comment by tianon** [comment]
@OddBloke `rolling` sounds OK to me!  Is there a term Canonical uses for this sort of thing elsewhere? (probably just `latest`, huh? :disappointed:)

**Comment by tianon** [comment]
https://wiki.ubuntu.com/Releases talks about "Regular releases", but "Ubuntu Regular" really doesn't make much sense (and implies things about "non-regular" Ubuntu that simply aren't true, IMO :laughing:)

**Comment by OddBloke** [comment]
On 17/02/17 14:06, Tianon Gravi wrote:
> @OddBloke <https://github.com/OddBloke> |rolling| sounds OK to me! Is
> there a term Canonical uses for this sort of thing elsewhere? (probably
> just |latest|, huh? 😞)

Yeah, we don't really have a term that means latest other than "latest".
;-)  I'd go with rolling.
