### ISSUE TITLE
Official ArchLinux Support

### ISSUE THREAD

**Issue by bebehei** [docker-library/official-images#2488]
Could you please add official ArchLinux support?

On docker hub, there is [base/archlinux](http://hub.docker.com/r/base/archlinux/), which got its last update 1.5 years ago. There is no other image with higher reputation.

The sad thing: it is 100% unusable, but for a search for *archlinux*, it is ranked best in every metric. Additionally, that guy used a sneaky username: `base`. How on earth should a user (or especially a newbie) think, that `base/archlinux` image is still not official and also not usable? You might have to have some experience to actively falsify this.

It might be a good choice - and the Archlinux-docker community will thank you - to have an official ArchLinux docker image: Could you please add an offical docker image for ArchLinux?

**Comment by tianon** [comment]
If there were a member of the ArchLinux community willing to step up and maintain an official image, we'd love to have it!  One of our first criteria for reviewing a new image is "associated with or contacted upstream?", so having upstream's approval or support in some way would be the first step.

I'm going to close this since it's not really actionable as-is, but hopefully someone from the Arch community can be convinced to step up and maintain an image!  I'm happy to help with some of the details, but as I'm not a user of Arch, I wouldn't personally be comfortable building or maintaining this base image myself. :+1: :heart:

**Comment by bebehei** [comment]
Sad news, but I appreciate your clear answer! So I may reach out and find an Arch TU to get this going on. Thank you for your support!

**Comment by bebehei** [comment]
@tianon I've got some other questions for you:

I always thought, that the `library`-folder all official images reference an repository on dockerhub with a specific image ID. After looking into the folder again, I've seen that there are only git-commits referenced.

- Does an official image always have to get built fully out of a git-repo?
- If yes, how to handle rolling release distros like arch? Updating a tarball inside a git-repo on a daily/weekly basis inside is horrible for git.

**Comment by yosifkit** [comment]
Sorry for the slow reply.  I must've missed your questions.

> Does an official image always have to get built fully out of a git-repo?

yes

> If yes, how to handle rolling release distros like arch? Updating a tarball inside a git-repo on a daily/weekly basis inside is horrible for git.

On the timing side, since the official images require a PR with review for each update, daily updates would not be tenable but I think weekly could work.

As for handling tarballs in git, @tianon has moved to using a branch for each architecture and ensures that that there is only 1 commit on each branch with a force push of each new set of tarballs. As long as it is a single commit, cloning is relatively fast.  We'd like to use `git-lfs`, but they don't support `git archive` (https://github.com/git-lfs/git-lfs/issues/1322).

See https://github.com/debuerreotype/docker-debian-artifacts for how the Debian artifacts are handled. There is also an older discussion here: https://github.com/docker-library/official-images/pull/179#issuecomment-56233346.

**Comment by kpcyrd** [comment]
I'm very interested in seeing this happen and help where possible. There's currently an "official" image maintained by an archlinux TU here: https://hub.docker.com/r/archlinux/base/ The repo for this image is located here: https://github.com/archlinux/archlinux-docker

If you send me instructions what needs to be done I'm going to prepare patches.

**Comment by bebehei** [comment]
@kpcyrd 

> > Does an official image always have to get built fully out of a git-repo?
>
> yes

The current approach of the official repository does not respect this. It's required to startup outside of a container first.

**Comment by tianon** [comment]
@kpcyrd indeed, as @bebehei points out, we need the entire build context for the image build committed to Git ATM (@yosifkit's comment above has a bit more details: https://github.com/docker-library/official-images/issues/2488#issuecomment-335632340)

What I'd recommend is creating a separate branch on that repo (I usually name mine `dist` or `dist-ARCH` like `dist-amd64`) and have that be a force-push copy of master with a single additional commit which adds the latest tarball.  Once something like that is in place (and hopefully created in an easily repeatable manner), then it's simply a matter of going through the steps in https://github.com/docker-library/official-images#contributing-to-the-standard-library (PR here to add `library/archlinux` and PR to the docs repo to add an `archlinux` folder).

Here's a few example repos:

- https://github.com/tianon/docker-brew-ubuntu-core  
  (https://github.com/docker-library/official-images/blob/master/library/ubuntu)

- https://github.com/fedora-cloud/docker-brew-fedora  
  (https://github.com/docker-library/official-images/blob/master/library/fedora)

- https://github.com/gliderlabs/docker-alpine  
  (https://github.com/docker-library/official-images/blob/master/library/alpine)

**Comment by bebehei** [comment]
@pierres Are you willing to make the official ArchLinux Images part of the library?
