### ISSUE TITLE
tomcat: CVE-CVE-2016-8745

### ISSUE THREAD

**Issue by pts-dorianpula** [docker-library/official-images#2576]
CVE-2016-8745: http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-8745

Affects:
- [tomcat 8.0-jre7](https://github.com/docker-library/tomcat/blob/e5ee9fb792276e4558733e22b3fb02af9de91ef5/8.0/jre7/Dockerfile)
- [tomcat 8.0-jre7 alpine](https://github.com/docker-library/tomcat/blob/3c72bd6721ab6645badc72c164cbe6f3a8970bdb/8.0/jre7-alpine/Dockerfile)
- [tomcat 8.0-jre8](https://github.com/docker-library/tomcat/blob/e5ee9fb792276e4558733e22b3fb02af9de91ef5/8.0/jre8/Dockerfile)
- [tomat 8.0-jre8 alpine](https://github.com/docker-library/tomcat/blob/3c72bd6721ab6645badc72c164cbe6f3a8970bdb/8.0/jre8-alpine/Dockerfile)

[Issue resolved in Tomcat 8.0.40](https://tomcat.apache.org/security-8.html).

**Comment by pts-dorianpula** [comment]
Currently need the Tomcat project to officially release 8.0.40: https://tomcat.apache.org/download-80.cgi

**Comment by yosifkit** [comment]
We have an automated job that runs [`update.sh`](https://github.com/docker-library/tomcat/blob/e4ffae4e6e76e979ad524970f80984ee4cff88d7/update.sh) and it was failing because the Apache mirrors did not have the new version when it tried to build test the new version.  It has now added https://github.com/docker-library/tomcat/commit/437ad1d98f2ca7667df856d13922b23a22b719d0 and https://github.com/docker-library/tomcat/commit/e4ffae4e6e76e979ad524970f80984ee4cff88d7 to update Tomcat 7 and 8, respectively.  The next step in the process is for us to make the PR here that updates the commits in the `library/tomcat` file using the `generate-stackbrew-library` script from the tomcat repo.  I'll try to get one up shortly.
