### ISSUE TITLE
Why centos 6.7  has no passwd file ??

### ISSUE THREAD

**Issue by Fiseast** [docker-library/official-images#2646]
I have pulled centos:6.6 centos:6.7 centos6.8 images and excute "docker run -it centos:6.7 /bin/bash".
But I found "command not found" in centos6.7 when I excute "passwd".
Why centos 6.7 has no passwd file ?

**Comment by yosifkit** [comment]
This might be better to file in the [centos image](https://github.com/CentOS/sig-cloud-instance-images/issues) repo.  Many of the maintainers do not actively watch this general repo.  You can install it with `yum install passwd`.

> images with minor version tags that correspond to install media are also offered. These images DO NOT receive updates as they are intended to match installation iso contents. If you choose to use these images it is highly recommended that you include RUN yum -y update && yum clean all in your Dockerfile, or otherwise address any potential security concerns.
> \- Docker Hub ([src](https://github.com/docker-library/docs/tree/8353eb4c9853e15d26544ec0bb5878fd77742d28/centos#minor-tags))

Given that the point releases are just reflections of the install media, it may make more sense to just use the `centos:6` image since it contains updates and is periodically regenerated to stay up to date.

**Comment by tianon** [comment]
Indeed, most of the individual image maintainers don't follow this repo (so re-filing over where @yosifkit noted would be more appropriate).  Thanks! :+1:

**Comment by Fiseast** [comment]
Thanks! @yosifkit
