### ISSUE TITLE
Official Rapidoid image not visible in the Docker Store

### ISSUE THREAD

**Issue by nmihajlovski** [docker-library/official-images#2784]
While most of the official images can be found on Docker Store (having "Docker" as the publisher), the official Rapidoid image isn't listed there.

Am I missing something here? Should I go through the "Publish" process on Docker Store?

**Comment by yosifkit** [comment]
It should happen with all the Official Images automatically.  cc @wol4max to see what process we need to go through to get it fixed.

**Comment by nmihajlovski** [comment]
Thanks @yosifkit for the quick response.

@wol4max, could you please provide some info / advice regarding this? I see many new official images aren't listed in Docker Store.

**Comment by tianon** [comment]
@nmihajlovski it might be a good idea to open an issue with Docker Support (via https://support.docker.com/), since I think they'll be able to file this in the appropriate internal tracker and maybe get more attention on it -- I'm going to close this issue since there's not much we (the official images team) can do to help.  Sorry! :heart:

**Comment by nmihajlovski** [comment]
This issue was resolved few days ago, thanks to Docker Support.

I apologize for not closing this immediately.

**Comment by tianon** [comment]
Glad to hear it! 👍
