### ISSUE TITLE
node is not built for multiarch

### ISSUE THREAD

**Issue by xobs** [docker-library/official-images#3105]
The armhf "multiarch" repo mentions that armhf/node is deprecated, in favor of arm32v7 and arm64v8.  However, there are no such official images.

node should be built for these architectures, so as to reflect what the documentation says.

**Comment by yosifkit** [comment]
The previous builds under armhf/node were part of our initial experiment into mutli-arch builds and did not involve the node working group that maintains the image. Now that we have support for specifying architecture in this repo, the docker-node working group can work to add whatever architectures that they want to support.

Would you like to go file an issue in their [repo](https://github.com/nodejs/docker-node/issues) and link to the [docs](https://github.com/docker-library/official-images/tree/5bed4180065646c6c586a5fa6bf50c6bb12d20f0#multiple-architectures) and the set we have already added as examples? ie docker-library/rabbitmq#167 and the list it contains.  Not sure if they will duplicate the changes, since they may not want to add `bashbrew` as a dependency for `generate-stackbrew-library.sh`.

**Comment by xobs** [comment]
It looks like there's a similar bug under nodejs/docker-node#207 for PPC.  I'll update that bug.

The surprising thing is that the armhf/node documentation mentioned the need to use the arm32v7 and arm64v8 versions, which don't exist.
