### ISSUE TITLE
MediaWiki

### ISSUE THREAD

**Issue by davidbarratt** [docker-library/official-images#3271]
It would be really helpful if there was an official docker image for [MediaWiki](https://www.mediawiki.org/wiki/MediaWiki).

There is some work that others have done here:
https://github.com/wikimedia/mediawiki-docker

And there is an existing issue here:
https://phabricator.wikimedia.org/T92826

But there is nothing that is as lightweight and automated as the Drupal & WordPress images (afaik)

I can certainly help with this if needed, but wanted to get the green light first. :)

**Comment by magol** [comment]
+1

**Comment by davidbarratt** [comment]
I created a very simple image to start with:
https://hub.docker.com/r/davidbarratt/mediawiki/

**Comment by tianon** [comment]
The first step would be to get in touch with the MediaWiki folks and
determine whether they're interested in supporting, contributing to, or
allowing for an image to be added to the official images program.  Since
they've already got something they've worked on and actively
support/maintain, it's probably worth collaborating with them on that, and
seeing whether they're interested in pushing it into the official images.

**Comment by davidbarratt** [comment]
Well I can't speak for everyone, so I'll let @d00rman weigh in.

**Comment by tianon** [comment]
Oh apologies, didn't realize you're with @wikimedia :sweat_smile: (we _often_ get requests from folks asking why we don't have X, and have to explain that we've had some unpleasant run-ins with upstreams that weren't happy with us, so we always err on the upstream-first side these days :heart:)

If it turns out this is something desirable, I think https://github.com/docker-library/official-images#contributing-to-the-standard-library is the best place to start (and looking at examples of other images in https://github.com/docker-library/official-images/tree/master/library). :+1:

I'd also add that we're happy to help/support in any way we can! :metal:

**Comment by addshore** [comment]
I also +1 this push and support! :)
Getting a nice clean and simple mediawiki docker image would be wonderful!

**Comment by davidbarratt** [comment]
Here's the PR #3281 3281

**Comment by davidbarratt** [comment]
@tianon 

The only thing left to do (afaik) is to transfer https://github.com/davidbarratt/mediawiki-docker to your org. Would you mind facilitating that?

**Comment by tianon** [comment]
Ideally it would live in a mediawiki org (which makes the upstream ties
even more obvious), but if you'd rather have it in docker-library and have
us co-maintain, we're willing to do that (and we're willing to do that as
well even if it moves to a mediawiki org).

**Comment by davidbarratt** [comment]
@tianon 

It would be really helpful if your organization would help co-maintain. I certainly would like to help, but strictly speaking, it's outside of my day-to-day responsibilities. I'll let @kaldari override me if he so chooses. :)

**Comment by davidbarratt** [comment]
@tianon

Also, if you want it on the @wikimedia org I can have a repo added (what should it be called?), but I think it's fine if it's on @docker-library

**Comment by tianon** [comment]
The name of the repo isn't really all that important (since it just leads eventually to a `GitRepo` line in this repo) -- some orgs use `docker`, some use `docker-SOFTWARE` or `SOFTWARE-docker`, etc.

If it lives under @wikimedia, it not only makes the maintenance/upstream ties more obvious, but also leaves it 100% under the control of upstream -- if you want us to co-maintain, just ensure @tianon, @yosifkit, and @docker-library-bot have commit bits.

**Comment by davidbarratt** [comment]
ok, the repo is now moved to
http://github.com/wikimedia/mediawiki-docker

Let me know if there's anything else you need!

**Comment by tianon** [comment]
This was completed in https://github.com/docker-library/official-images/pull/3281. :smile: :+1:
