### ISSUE TITLE
'docker pull docker.io/fedora' fails to pull the right arch on alternative architectures 

### ISSUE THREAD

**Issue by paulwhalen** [docker-library/official-images#3299]
When testing docker on alternative arches (armhfp, aarch64), using the command 'docker pull docker.io/fedora' appears to pull the wrong arch. 

[root@localhost ~]# docker pull docker.io/fedora
Using default tag: latest
Trying to pull repository docker.io/library/fedora ... 
sha256:b27b4c551b1d06be25a3c76c1a9ceefd7ff189f6f8b1711d3e4b230c2081bff3: Pulling from docker.io/library/fedora
4db9daa7aafd: Pull complete 
Digest: sha256:b27b4c551b1d06be25a3c76c1a9ceefd7ff189f6f8b1711d3e4b230c2081bff3
Status: Downloaded newer image for docker.io/fedora:latest

sudo docker run -it --rm docker.io/fedora bash
..
standard_init_linux.go:178: exec user process caused "exec format error"

**Comment by maxamillion** [comment]
@tianon I was under the impression that this would "just work" because of the way the manifest lists are composed. Is there something I need to do on my end to enable this?

**Comment by tianon** [comment]
For this to work _automatically_, we need manifest lists (https://github.com/docker-library/official-images/issues/2289) -- we can't turn those on yet because the signing and scanning infrastructures aren't prepared for them yet, so unfortunately, this is currently working-as-designed. :disappointed:

(So until that's fixed, you'll need to use `arm32v7/fedora` or `arm64v8/fedora` explicitly as described at https://github.com/docker-library/official-images#architectures-other-than-amd64, or the temporary `trollin/fedora` which is a manifest list and will be what `library/fedora` becomes eventually.)

**Comment by maxamillion** [comment]
@tianon Thanks for the info! I thought the manifest lists were enabled already. TIL. :)
