### ISSUE TITLE
Use `--squash` for images

### ISSUE THREAD

**Issue by SimenB** [docker-library/official-images#3334]
Would it be possible to start using `--squash` when building the official images? I'd love to be able to drop all the `&& \` in the node docker files, and stop worrying so much about layers and just caring about cleaning up.

https://docs.docker.com/engine/reference/commandline/build/#squash-an-images-layers-squash-experimental-only

(semi-related, is there an issue I can track for when we can start to use multi-stage builds?)

**Comment by yosifkit** [comment]
This would possibly double or more the storage requirements on our build servers and prevent users from being able to share layers between image updates and across versions thus increasing their storage needs as well.  It will also make it even harder to clean up old images, since we would have to track the non-squashed version of each image along with its flat version.

You may be interested in the progress of https://github.com/moby/moby/issues/34423 which will hopefully make multi-line `RUN` lines much easier to use.

No issue that I recall tracking multi-stage builds in official-images.

**Comment by emilevauge** [comment]
Added https://github.com/docker-library/official-images/issues/3383 to track multi-stage builds ;)

**Comment by cpuguy83** [comment]
Also it looks like `--squash` may be removed since multi-stage build largely serves the same purpose.

**Comment by tianon** [comment]
Agreed, good call 👍

In either case, we'll definitely not be using squash here; will leave discussion of multi-stage to that new issue.

**Comment by SimenB** [comment]
Multi-stage is definitely better that squash. My thought was that one is available now, one is not 🙂
 Highly in favor of multi-stage builds!

>Also it looks like --squash may be removed since multi-stage build largely serves the same purpose.

Could you link to some issue tracking that (if it exists)?

**Comment by cpuguy83** [comment]
https://github.com/moby/moby/issues/34565
