### ISSUE TITLE
Running crate:2.1.7 is starting 2.1.6

### ISSUE THREAD

**Issue by chaudum** [docker-library/official-images#3467]
Hi,

We encountered following issue:

After the last update of CrateDB (see https://github.com/docker-library/official-images/commit/ea085764a5d8ca2cca29690ec74cd3fa274b0517), `crate:latest`, `crate:2.1` and `crate:2.1.7` should run CrateDB 2.1.7 - based on commit https://github.com/crate/docker-crate/commit/21b3ccb1b09845558fefc3a822132ecb1c8161e6

However, when running this tag, CrateDB version 2.1.6 is starting

```
$ docker run --rm -ti crate:2.1.7 crate -v
Version: 2.1.6, Build: ef717e0/2017-08-29T11:08:06Z, ES: 5.4.3, JVM: 1.8.0_121
```

So I checked if the [tarball](https://cdn.crate.io/downloads/releases/crate-2.1.7.tar.gz) of CrateDB version 2.1.7 is corrupt or containing a wrong version, but it's correct:

```
$ bin/crate -v
Version: 2.1.7, Build: 1c334ef/2017-09-14T09:49:00Z, ES: 5.4.3, JVM: 1.8.0_144
```

Any ideas?

**Comment by tianon** [comment]
Doh, looks like the new Crate version is failing to build due to keyserver flakiness -- I've restarted the build again.  The new tags being updated with the old bits is a side effect of https://github.com/docker-library/official-images/issues/2289 -- we have some optimizations in place which assume the "most specific" tag is the first listed, which in `crate`'s case is `latest`.

I'll send a PR in a moment to update `library/crate` to the newer file format and to adjust the order of the tags so we avoid doing pushing the wrong bits like this in the future (and I'll watch and restart the official build until it succeeds).

**Comment by tianon** [comment]
Confirmed fixed and new PR opened at https://github.com/docker-library/official-images/pull/3469 to help ensure it doesn't happen again. :+1:

```console
$ docker run -it --rm crate:2.1.7 crate -v
Unable to find image 'crate:2.1.7' locally
2.1.7: Pulling from library/crate
019300c8a437: Already exists 
7016202d4a29: Pull complete 
96b9a6c17b1f: Pull complete 
75274f044a6f: Pull complete 
b0d87e933ea0: Pull complete 
801f25af85e8: Pull complete 
ce022563b10f: Pull complete 
690dc93ea6ab: Pull complete 
Digest: sha256:5594a1a1841ffc0c137a9534cd2b6d693e5ac1875cd0f5ab41f8ab3fadafc531
Status: Downloaded newer image for crate:2.1.7
Version: 2.1.7, Build: 1c334ef/2017-09-14T09:49:00Z, ES: 5.4.3, JVM: 1.8.0_121
```

**Comment by chaudum** [comment]
@yosifkit @tianon thanks for your support!
