### ISSUE TITLE
Standard set of labels for official images

### ISSUE THREAD

**Issue by Djelibeybi** [docker-library/official-images#3540]
Hey librarians!

Is there a documented set of labels we should be using in the `Dockerfile` of an official library image? Currently, we don't have any labels for the Oracle Linux image and my (admittedly brief) scan of other official base OS (`FROM scratch`) images shows almost zero consistency.

Using labels seems to be 👍 so I just want to make sure I'm using either the _right_ labels or at least the _best_ labels.  😄

**Comment by tianon** [comment]
Honestly, I find labels on base images to be irritating, especially since they're all inherited by any image `FROM` the base (just like `MAINTAINER` of old, which they descended from), and prefer to consider them something useful for users to organize their images and/or their deployments.

As for the official stance, we don't have one -- if an image maintainer chooses to apply `LABEL`s to their image, that's their prerogative (a few examples that do are [CentOS](https://github.com/CentOS/sig-cloud-instance-images/blob/16dab97b0ce72b1db7a2f9b02c76e452cb0a63cb/docker/Dockerfile#L4-L7), [Silverpeas](https://github.com/Silverpeas/docker-silverpeas-prod/blob/03bd2800e83bf262d07b53f067758115fa6f05fc/Dockerfile#L70), and [Træfɪk](https://github.com/containous/traefik-library-image/blob/d807e0f3692209f960bb2567e7890453a190c899/scratch/amd64/Dockerfile#L7-L13)).

I think the argument for them is slightly stronger in the case of a single bit of software (like Træfɪk), but even there I'm indifferent (and the added need to then update both the software contained in the image and the metadata of the image concurrently is irritating, although trivially scriptable -- basically just one more place for information to potentially become out-of-sync).

**Comment by tianon** [comment]
I literally just noticed your "Hey librarians!" here :100: :laughing: :heart:

**Comment by tianon** [comment]
Closing since this isn't something we plan to implement any time soon.  If that ever changes, we're happy to re-open. :+1:

**Comment by alexbozhenko** [comment]
Hi, @tianon and @yosifkit.
For images that do set oci labels, the image is self-describing, e.g.
`# docker  pull solr && docker image inspect solr --format='{{json .Conf
ig.Labels}}' | jq '.'`
<details>

```
Using default tag: latest
latest: Pulling from library/solr
Digest: sha256:60f3fbc0911eabd3ad0a6efb2f465b6e68d35ed487bda7b6bbf6339b9b5a39e6
Status: Image is up to date for solr:latest
docker.io/library/solr:latest
{
  "org.opencontainers.image.authors": "The Apache Solr Project",
  "org.opencontainers.image.description": "Solr is the blazing-fast, open source, multi-modal search platform built on Apache Lucene. It
 powers full-text, vector, and geospatial search at many of the world's largest organizations.",
  "org.opencontainers.image.documentation": "https://solr.apache.org/guide/",
  "org.opencontainers.image.licenses": "Apache-2.0",
  "org.opencontainers.image.ref.name": "ubuntu",
  "org.opencontainers.image.source": "https://github.com/apache/solr",
  "org.opencontainers.image.title": "Apache Solr",
  "org.opencontainers.image.url": "https://solr.apache.org",
  "org.opencontainers.image.version": "9.10.0"
}
```
</details>


For images that do not set those labels, it may become a tricky task to find out _what_ that image on hand is, since `docker image inspect` would not show any high-level metadata. (Is there a better way?)

So I looked at all official images, and looks like around 30% of them set some `org.opencontainers.` label:
https://gist.github.com/alexbozhenko/108f9c9863e1e8dfdd1de8981249094d#file-gistfile1-txt-L860-L864

And i also looked at top 30 non-official images, about half set the tags:
https://gist.github.com/alexbozhenko/01c7afa5890661581b96eec64d654a1e

Would it be possible to re-consider this, and maybe give a recommendation for image authors to set the labels, which seems like a good thing to have?

**Comment by tianon** [comment]
Unfortunately, labels have awful behavior, most especially that they're automatically inherited by any dependent image that does `FROM`, with no way to "unset" them (only overwrite).  This is exactly why the OCI designed annotations in the way that they did (and they're intentionally not inherited).

I've even gone so far as to suggest that the OCI should deprecate "labels" entirely, although (probably lucky for a lot of folks) I haven't gotten much traction with that idea. :smile:
