### ISSUE TITLE
ubuntu-upstart:12.04: Can't install cron

### ISSUE THREAD

**Issue by vasi** [docker-library/official-images#355]
```
root@7ee4f5fd534e:/# apt-get install cron
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  anacron logrotate checksecurity exim4 postfix mail-transport-agent
The following NEW packages will be installed:
  cron
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 85.0 kB of archives.
After this operation, 308 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ precise-updates/main cron amd64 3.0pl1-120ubuntu4 [85.0 kB]
Fetched 85.0 kB in 0s (403 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package cron.
(Reading database ... 8311 files and directories currently installed.)
Unpacking cron (from .../cron_3.0pl1-120ubuntu4_amd64.deb) ...
Setting up cron (3.0pl1-120ubuntu4) ...
Adding group `crontab' (GID 103) ...
Done.
start: Job failed to start
invoke-rc.d: initscript cron, action "start" failed.
dpkg: error processing cron (--configure):
 subprocess installed post-installation script returned error exit status 1
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@7ee4f5fd534e:/# 
```

Note also that the `runlevel` command returns `unknown`. Is that correct?

**Comment by fago** [comment]
I tested the same with the latest image and got the same error:

`root@7bf826fb1437:~# apt-get install cron
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  anacron logrotate checksecurity exim4 postfix mail-transport-agent
The following NEW packages will be installed:
  cron
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 85.0 kB of archives.
After this operation, 308 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ precise-updates/main cron amd64 3.0pl1-120ubuntu4 [85.0 kB]
Fetched 85.0 kB in 0s (581 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package cron.
(Reading database ... 8311 files and directories currently installed.)
Unpacking cron (from .../cron_3.0pl1-120ubuntu4_amd64.deb) ...
Setting up cron (3.0pl1-120ubuntu4) ...
Adding group `crontab' (GID 103) ...
Done.
start: Job failed to start
invoke-rc.d: initscript cron, action "start" failed.
dpkg: error processing cron (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 cron
E: Sub-process /usr/bin/dpkg returned an error code (1)
`
It works when you set the container to run in privledged mode though.

**Comment by tianon** [comment]
I think this is an AppArmor/SELinux issue, especially if "--privileged"
works.  On the flip side, you're running an init system, and "--privileged"
is giving it full access to the host, which has been known to cause very
serious issues in the past.  It would be a better idea to set up a new
apparmor profile for your upstart container, and use "--security-opt" (
https://docs.docker.com/reference/run/#security-configuration).
