### ISSUE TITLE
Update Joomla Version

### ISSUE THREAD

**Issue by rainerangermeier** [docker-library/official-images#3699]
Currently Joomla 3.8.0 is available: commit [7f460a60ab1d239f55a38934abe530294d4fab62](https://github.com/joomla/docker-joomla/commit/7f460a60ab1d239f55a38934abe530294d4fab62)

The latest release at the moment is 3.8.2. 

In addition to that, the installation check on container startup in docker-entrypoint.sh changed at [43e546ea66a359b8e7b10213fae5d8e30bf5df16](https://github.com/joomla/docker-joomla/commit/43e546ea66a359b8e7b10213fae5d8e30bf5df16). Without this fix joomla will be installed every time you start the container.

**Comment by tianon** [comment]
This repository is the general repo for the official images, and most of our image maintainers don't follow it directly due to a high volume of unrelated PRs -- I'd recommend poking the maintainers over in https://github.com/joomla/docker-joomla/pull/34 to ask them to update `library/joomla` here so that the official image is updated as well.
