### ISSUE TITLE
How to hide tags

### ISSUE THREAD

**Issue by arthurdm** [docker-library/official-images#4064]
Is there a way to hide tags from the `tags` tab of an image?

For instance, in WebSphere Liberty (https://hub.docker.com/_/websphere-liberty/) the main Docker Hub page (`Repo info` tab) shows the current supported tags, but switching to the `Tags` tab we see old tags that we would like to remove, such as `common`, and `8.5.5`.  

Is there a way to do this?

**Comment by yosifkit** [comment]
The "last updated" is two years ago, so I would think users know that they exist only as a snapshot of a past release.  We view the tags section on the Docker Hub as an archive of all past releases; which is why we generate the "Supported Tags and respective Dockerfile links" section in the description to point users to the actively maintained set of tags (generated from `library/` file in this repo).

**Comment by arthurdm** [comment]
Thanks @yosifkit 

I noticed that the UI of the `Tags` page has changed (only saw the new version today), and now it separates between Scanned and Unscanned Images.    I am guessing the Supported Tags == Scanned Tags always?

**Comment by tianon** [comment]
That actually has been that way for a while, but changes based on whether
you're logged in, and might go away with the scanning changes that are
coming up (not sure).

**Comment by arthurdm** [comment]
Thanks @tianon - can you confirm if these changes that are coming up would allow for old tags to become invisible (in the sense that one can still `pull` it, but won't see it listed in `Tags`)?

**Comment by tianon** [comment]
I'm sorry, but I can't confirm anything around that -- we don't have any visibility into those development processes, timelines, or decisions (for the most part, we're consumers of the Hub on the same level as any other project or user).

I would imagine that tag hiding _won't_ be part of the change, and that the "Tags" tab will simply list everything as it does today for unauthenticated users, but that's simply a guess.  Sorry!

(I'm going to close, since this is more of a Hub thing, and not something we have any direct control over. :heart:)
