### ISSUE TITLE
Question about automatic image builds

### ISSUE THREAD

**Issue by arthurdm** [docker-library/official-images#4177]
Hi - when something changes in a base image (for example, `ibmjava:8-jre` is a base image for `websphere-liberty`), our official images get automatically rebuilt, right?

Is it possible to get a notification when such rebuild happens?

Thanks.

**Comment by yosifkit** [comment]
Sorry for the slow reply. :bowing_man:

They are automatically rebuilt.  All the builds are done via Jenkins.  A change to `official-images` triggers an image build, when that build finishes, any dependent images are triggered for builds as well (per architecture).  This could happen multiple times since some tags from the first image could've failed to build and so it would get scheduled again later.  Build failures are ignored so that other updates don't get held back by one failing tag.  We unfortunately don't have any notification system plugged into the jenkins servers.

You can view the arch specific builds for a particular image like `ibmjava` here: https://doi-janky.infosiftr.net/job/multiarch/view/images/view/ibmjava/.
