### ISSUE TITLE
Guidance on using build args in official images

### ISSUE THREAD

**Issue by arthurdm** [docker-library/official-images#4224]
Hi,

I would like to know if there's some guidance or samples from Docker's Official libraries on using build arguments in official images, in particular to toggle the `FROM` statement, as described here https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact

For example, the Open Liberty official image has a few different tags where the only difference is the JRE they start from.  If we had an `ARG` that would mean we could combine those into a single dockerfile, varying which `--build-arg` is used.  But the question is: can Docker Inc do a `docker build` using different build args (to achieve different tags), since they build the official images?

**Comment by yosifkit** [comment]
Currently there is no way to use build args in official images. There was a PR to add them and I was amenable to the idea then, but now I am mostly against them.  If we did allow build args it would make the link to the Dockerfiles on the Hub description less useful since there is other context that the user must account for that would not be obvious to find.

In most of the repos we maintain, we create a common Dockerfile template and just use `sed` via an update script to input version specific information (like https://github.com/docker-library/cassandra/).

**Comment by 7AC** [comment]
Can you add a mention of this and any other limitation of regular dockerfile syntax within bashbrew? In particular looks like the following fails the build:

```ARG FOO 123
FROM bar:${FOO}
```
