### ISSUE TITLE
Docker Hub vs. Docker Store

### ISSUE THREAD

**Issue by sonicdoe** [docker-library/official-images#4475]
I’m opening this issue here because this repository contains a lot of links to [hub.docker.com](https://hub.docker.com) and it seems to be the most appropriate in regards to official Docker images.

Currently, when I visit any of the official repositories in the Docker Hub, I’m seeing a blue banner that [Docker Store](https://store.docker.com) is the new place to discover public Docker content. For example, on [hub.docker.com/_/hello-world/](https://hub.docker.com/_/hello-world/):

![hello-world is now available in the Docker Store, the new place to discover public Docker content.](https://user-images.githubusercontent.com/652793/41642336-46ecc216-7468-11e8-93a7-ec0b31ff873d.png)

I’m wondering if the Docker Store is also the new (and preferred place) *for official images*. A few days ago I opened https://github.com/nodejs/nodejs.org/pull/1699 and we are not sure whether we should link to Docker Hub or Docker Store. Any official recommendation would be quite helpful.

**Comment by tianon** [comment]
We always link to Docker Hub because that's where we push the images -- the banner you've noted has been on the official images for almost as long as Docker Store has existed, and I think it's still not to the point where they're comfortable redirecting folks automatically.  Last I knew, it was still referencing content form the Hub directly (hence Hub is still the canonical location for the content itself).

However, this isn't anything official -- we're not on that team (nor involved with them much), so this is all based on what we know and have seen publicly.

**Comment by c0b** [comment]
I've often seen the same images in Docker Store are 2or3 months late than Docker Hub in synchronization, not sure why, but it looks like Docker Store is more commercial oriented vs Docker Hub is community oriented;  even you guys are in the same company Docker Inc  but looks like zero cross-team communications

**Comment by c0b** [comment]
hence I use Docker Hub always.

**Comment by tianon** [comment]
We're an official Docker project, but (we the maintainers) are not part of
Docker Inc directly.

**Comment by tianon** [comment]
(Closing, since there's not really anything actionable here. :heart:)

**Comment by tianon** [comment]
Just to add an additional bit of data (pointed out to me over in https://github.com/nodejs/nodejs.org/pull/1699), the banners are now removed from Hub. :+1:
