### ISSUE TITLE
What's the logic behind images licenses?

### ISSUE THREAD

**Issue by csandanov** [docker-library/official-images#5065]
I see that MariaDB image is under GPL-2.0 license, which I guess make sense considering MariaDB itself is GPL-2 and the docker image is a binary redistribution of MariaDB. On the other hand, PHP image is under MIT license but the PHP itself is under [PHP 3.0.1](http://php.net/license/3_01.txt) which is clearly not compatible with MIT. So, what's the logic behind the licenses? Why not just add appropriate license file within the image and make all images MIT since the images repositories do not contain code of the applications they distribute?

**Comment by tianon** [comment]
Are you referring to the license in the Git repository for each image, or
the "license.md" that becomes part of the image documentation on Docker Hub?

The license in the repository is only for the "code" in the repo (as in,
the Dockerfiles themselves, whatever associated small scripts, etc), and in
most cases for the docker-library repos we've tried to match the upstream
license in order to ease the flow of contribution from our repo to upstream
if that's something they desire.  For repos that are not under
docker-library, the license is up to individual maintainer discretion
(which in many cases _is_ upstream).

The "license.md" text for Docker Hub is intended to be merely
informational, typically with a pointer to further reading.

**Comment by csandanov** [comment]
I'm referring to the image repository code. Sometimes official images don't work for me for some reasons, e.g. alpine-based MariaDB so I borrow some helper scripts, as a result I had to change license from MIT to GPL-2.0. 

> to ease the flow of contribution from our repo to upstream

As I understand this is for cases when someone contributes a patch in the image repository (e.g. patches for MariaDB to make it compatible with musl)  and maintainers of the applicatoin (MariaDB) decided to merge this patch. But if MariaDB image repository license is MIT (as opposed to MariaDB's server GPL 2.0) they still can do it since GPL-2.0 (and other restrictive licenses) are compatible with MIT.

I suggest to use MIT license for all images repositories since it idealogically suits better for images (correct me if I'm wrong), in everyone's interest to have more developers use images so we can all report issues to the official image repo and then to upstream.

**Comment by csandanov** [comment]
Regarding the license of the software redistributed via images perhaps the good practice would be to copy the license of the software under `/usr/share/doc` https://opensource.stackexchange.com/questions/7608/how-does-linux-with-pre-installed-binaries-comply-with-binary-redistribution-lic/7609#7609

**Comment by tianon** [comment]
Yep, see https://github.com/docker-library/repo-info for where we
automatically scrape/link to some of that information from the built images
themselves.

**Comment by tianon** [comment]
(Closing, since there doesn't appear to be anything actionable here.)
