### ISSUE TITLE
Do not rebuild images that are taged with a specific version

### ISSUE THREAD

**Issue by mikehaertl** [docker-library/official-images#557]
I see, that even if an image is tagged with a very specific version like `mysql:5.2.22` that image is rebuilt with new layer ids from time to time. This is very bad, because it basically means, that any child images get invalidated, even if nothing has changed for them. This causes a lot of extra builds, not to mention the additional network traffic for downloading the new builds.

I therefore suggest to make this a convention for all official images. If it's really not avoidable, then maybe you should add patchlevels like `mysql-5.2.22-p1`.

**Comment by psftw** [comment]
One of the reasons behind this could be that the Dockerfile which generates the image changes without the upstream software actually changing.  This can be for any number of reasons such as bugfixes or new features.  I agree it's not ideal, and should be avoided, but there is no other way around it in that scenario.  If the upstream software changes, it should be a new tag, and I think convention is followed.

**Comment by tianon** [comment]
This is intentional, and 100% by design.  A tag like `mysql:5.6.23` contains MySQL version 5.6.23 -- the actual image artifacts/layers might be rebuilt due to updates or improvements to the Dockerization (such as new optional entrypoint variables), but far more likely and more common are base image updates (ie, `debian:wheezy` is rebuilt to for updated packages which include security fixes), which we propagate upwards for what I hope are obvious reasons.

**Comment by mikehaertl** [comment]
Hmm, OK, thanks. Will have to consider this for my image workflow. Not sure if things like this should maybe be mentioned on the website. 

For my project I was trying to build a base image with all the complex build steps in it. So each developer in our team can start from there and only has to download this once. At least that was the idea. But if the `FROM` source of this base image changes, my plan doesn't really work out as our base image will also get invalidated from time to time. 

OT: Actually things like recommended image workflows/hierarchies for small/medium/large scale projects are the type of information which is really scarcely documented. I'm sure, many people would love to read more about this in the documentation.

**Comment by mikehaertl** [comment]
Another problem I still see is, that if a base image is changed, it always poses the risk of introducing BC breaking changes. So in worst case, after some month your Dockerfile suddenly may not build anymore, due to such a change. And there's nothing you can do about it.

So I still recommend to at least make some images immutable. How about this naming scheme:

 * mysql:5.6.23 - Mutable, may be updated
 * mysql:5.6.23-p1, mysql:5.6.23-p2 - Immutable! Using these tags will guarantee, that you always get the same image, once and forever

**Comment by psftw** [comment]
I don't see the suggested patch level strategy for official repos ever happening because it complicates the situation needlessly.  Official repos should be fairly stable over time and I would expect outright breakage to be extremely rare.  If you really want to achieve immutable tags, you are welcome to add additional tags to your own repositories.  Redistributing them to your internal team via a registry would also help achieve the efficiency you describe.  I've heard of using a weekly CI task to check if there is a new version of an image and then creating a new internal tag for it -- for the paranoid that don't want to upgrade without knowing exactly what changed.  Seems a bit overkill to me.  Does this answer help?

I agree it would be worth mentioning how this works in some documentation, so I'll try to fit that in soon and link to it here for your review.

**Comment by mikehaertl** [comment]
>  Redistributing them to your internal team via a registry would also help achieve the efficiency you describe.  I've heard of using a weekly CI task to check if there is a new version of an image and then creating a new internal tag for it.

Hmm, I'm not sure if I understand what you mean here. How would this redistribution work? And if it's only used internally, other users couldn't benefit from those tags?

> I agree it would be worth mentioning how this works in some documentation, so I'll try to fit that in soon and link to it here for your review.

Great, thanks.

**Comment by tianon** [comment]
To further elaborate on what @psftw described here, the recommended workflows for folks who need 100% immutable tags are:

1. Re-tag images directly into your own repository, thus controlling very directly their "update lifecycle".  For example, `docker pull mysql:5.5`, run tests on `mysql:5.5` to evaluate suitability for your purposes, `docker tag mysql:5.5 my/repo:mysql-5.5`, `docker push my/repo:mysql-5.5`, use `FROM my/repo:mysql-5.5` in your `Dockerfile`s (thus controlling absolutely when `my/repo:mysql-5.5` is updated).

2. Use content digests.  For example, [the current `mysql:5.5` image](https://github.com/docker-library/repo-info/blob/6c0b758a05c294a6682b83895b6da78712acf24e/repos/mysql/tag-details.md#mysql55) can also be pulled as `mysql@sha256:4fa6e27a0bb72ba9b7233955e891c91a38190d91a3a483d3075f126a7348fedd`, which unlike `mysql:5.5` will not change (cannot, in fact, since it's based on a hash of the content of the image itself).

I know it's kind of an old issue (Sorry!), but I'm thinking that noting this slightly more explicitly for posterity can't hurt. :smile: :+1:
