### ISSUE TITLE
Nagios Official Image Request

### ISSUE THREAD

**Issue by rogervila** [docker-library/official-images#5620]
Hello,

I would like to know which are the requirements to request an official image for a specific service, and the process to send a Pull Request with the `Dockerfile`

In this case, I would like to request a Nagios Official image.

Website: https://www.nagios.org/projects/nagios-core/

Thank you.

**Comment by tianon** [comment]
The process typically starts with contacting upstream and seeing if they're interested in having such a thing exist (we've had cases where they'd actually prefer such a thing does _not_ exist, which is why we ask contributors to get their involvement or at least their blessing first).

Then, make a decent Docker image (again, preferably with upstream's involvement/help, following their explicit deployment recommendations to accurately represent the "Upstream Experience").  Keep in mind that we'll use https://github.com/docker-library/official-images/blob/master/NEW-IMAGE-CHECKLIST.md as a guide when reviewing the PR, and that there's a lot of content at https://github.com/docker-library/official-images#contributing-to-the-standard-library (and a lot of other images to compare to for ideas).
