### ISSUE TITLE
Add generic checkbashisms test

### ISSUE THREAD

**Issue by J0WI** [docker-library/official-images#5877]
Check any shell script against `checkbashisms` to catch common syntax errors.

**Comment by yosifkit** [comment]
Are you asking about a new test for a set of images (test their entrypoints?), the test scripts themselves, or the other scripts in this repo?

Most of the shell scripts here are already bash, except where they needed to run in an alpine-based image that doesn't have bash.

**Comment by J0WI** [comment]
For the entrypoints.

It's also able to catch errors in regular bash scripts.
```
This script performs basic checks for the presence of bashisms
in /bin/sh scripts and the lack of bashisms in /bin/bash ones.
```

**Comment by tianon** [comment]
I think this is something we'd rather leave up to the individual image maintainers (and is likely easier for them to run directly from their source rather than trying to extract said source from the image).

(As for images under https://github.com/docker-library, I'm not personally a fan of either `checkbashisms` or `shellcheck`, FWIW.)
