### ISSUE TITLE
sha256 checksums

### ISSUE THREAD

**Issue by skippy** [docker-library/official-images#624]
are you open to adding checksum checks when downloading binaries?  If so, I'm happy to start sending PRs to add them

**Comment by yosifkit** [comment]
Are there specific images you are looking to improve?

**Comment by skippy** [comment]
well, most of them are linked, so I would track them down.  but I would start with the ones I tend to use, such as java, jruby, ruby, haproxy, nginx, postgres, elasticsearch, etc.  I just ask because I'm curious if adding checksums is a 'standard' docker would be willing to setup (and if not, why not... out of curiosity).  I realize checksums aren't perfect, but adding it, and https where available, doesn't hurt.  

thanks

**Comment by md5** [comment]
@skippy of the ones you mention, `java`, `nginx`, `postgres`, and `elasticsearch` are verifying GPG signatures and `haproxy` is checking an MD5 hash. It looks like `jruby` and `ruby` are not verifying their downloads.

**Comment by yosifkit** [comment]
We are definitely open to improving the security of the images.  As @md5 mentioned, we try to do pgp/gpg verification if possible, and when that is not available we do want to do checksums.  [Redis](https://github.com/docker-library/redis) has a good example.  We embed the sha hash into the Dockerfile using the update script so that there are two different people doing the verification, rather than downloading the hash during build, so it should be less susceptible to MITM attacks.

Feel free to PR away to all the `docker-library/`.  (Ruby sha verification is currently in a PR that we forgot to open earlier :disappointed: https://github.com/docker-library/ruby/pull/38)

**Comment by skippy** [comment]
I'll start opening PRs.  I've been making my own images but that is silly when it is just a change here and there.  I'll use GPG where possible, and then fall back to sha256 or MD5.

thanks everyone.

**Comment by yosifkit** [comment]
We look forward to your PRs.  Thanks for the help!
