### ISSUE TITLE
golang ARM images are failing to build

### ISSUE THREAD

**Issue by ibuildthecloud** [docker-library/official-images#6490]
The build is failing so golang 1.12.9 for ARM is currently unavailable.  Reference to jenkins job
https://doi-janky.infosiftr.net/job/multiarch/job/arm32v6/job/golang/

**Comment by yosifkit** [comment]
Yeah, our arm build servers tend to run out of space. Should be fixed shortly.

**Comment by tianon** [comment]
Indeed, builds are re-queued now and should be up soon; thanks for the poke. :heart:

@vielmetti I believe when our server was provisioned we discussed that our storage space could potentially be increased later if we determined we needed more?  Is that something that could be considered so that we run into this issue less frequently?  Is there an official process for requesting something like that?

**Comment by ibuildthecloud** [comment]
Thanks for the quick fix!
