### ISSUE TITLE
Question about build times

### ISSUE THREAD

**Issue by arthurdm** [docker-library/official-images#6697]
Hey guys,

Not an issue, just a question:  would you be able to let me know how long it takes to build the WebSphere Liberty and Open Liberty images?  

I am working on a re-design of our tags (because we have too many!) and it would be a good supporting fact if I knew how many hours it takes to build the multi-arch images for those 2 products.

Thx.

**Comment by yosifkit** [comment]
These will get some rough info on how long the last few builds took on each architecture. It's possible that some of the individual images were unchanged (and so used docker cache) or some of the jobs might be extra long since Jenkins leaves queue time in the total or they did take just that long.

- https://doi-janky.infosiftr.net/job/multiarch/view/images/view/open-liberty/
- https://doi-janky.infosiftr.net/job/multiarch/view/images/view/websphere-liberty/

**Comment by arthurdm** [comment]
thank you @yosifkit!
