### ISSUE TITLE
ENTRYPOINT+CMD vs CMD for easier arg passing

### ISSUE THREAD

**Issue by anapsix** [docker-library/official-images#692]
@yosifkit mentions usage of CMD alone is preferred "for the default command for all official base images" (see docker-library/nginx#12).
@ksnyde makes a point for ENTRYPOINT usage, since "in 99% of cases you'd want to just provide [nginx] switches as options to the run" next to image name which "mimics the signature of a bare-metal implementation".

Using Nginx as example, it's feels more natural to run `docker run -it nginx --help` instead of `docker run -it nginx nginx --help`.
Imho, the [legitimate] desire to make things more understandable is being circumvented by equally obscure alternative.
If both solutions are somewhat odd (I can see pros and cons of both), why not pick the more elegant, more concise one? .. while educating users on finer points of Docker command line argument usage. And use-cases of "--entrypoint" already revolve around advanced usage space. 
Of course one could go overboard with "doing things right": go-lang compiler and unused variables / libraries - yet that's another point for elegance [of sorts].

**Comment by Moghedrin** [comment]
![notearsjustsleep](https://cloud.githubusercontent.com/assets/1680823/7403169/4e309e32-ee90-11e4-8fc9-431c32245197.gif)

You are right, it does seem more natural to run `docker run -it nginx --help` instead of `docker run -it nginx nginx --help`. If that were the only consideration to be made, then *clearly* ENTRYPOINT would be the way to go.

That being said, we avoid this for several reasons. The first is that using the ENTRYPOINT command in this way breaks the natural behavior expected when running something like `docker run -it nginx bash`, or any other `docker run` command where I want CMD to be run. This is in accordance with the [official best practices](https://docs.docker.com/articles/dockerfile_best-practices/).

Furthermore, if we opt to use ENTRYPOINTs in the manner suggested, then it becomes impossible to run something like `bash` inside a container that includes a helper script ENTRYPOINT without ignoring that helper script entirely (as would happen in the case of setting the `--entrypoint="bash"`). While it is clear that only images which are built with helper scripts would have this particular issue, we feel it is more important for the official images to be consistent than save users six or seven keystrokes.

Finally, if adding flags, as per your example, is the prime usage for this behavior, then there is precedence to have checking for those a special case inside an ENTRYPOINT helper script, as seen in [MySQL's entrypoint.sh](https://github.com/docker-library/mysql/blob/master/5.7/docker-entrypoint.sh) and [MongoDB's entrypoint.sh](https://github.com/docker-library/mongo/blob/master/3.0/docker-entrypoint.sh). Between this and the issue regarding the overwriting of entrypoints above, the approach currently used is **strictly** more flexible and powerful than the approach of using the ENTRYPOINT as suggested.

If an image lacks a helper entrypoint script which would allow you to use it as you expect/wish, we would love it if you opened a pull request with the added script in question, so that we could review and discuss it.

**Comment by anapsix** [comment]
![good point](http://i.imgur.com/gnEqLs2.jpg)

Rolf, you had me at "shhhhh.."
Appreciate the thorough answer. I see your point..
A well made helper script can deal with the use case I've described.
