### ISSUE TITLE
Best practice for multi-arch images with different release schedules

### ISSUE THREAD

**Issue by dinogun** [docker-library/official-images#6927]
This is wrt the AdoptOpenJDK image. We currently release build binaries for different architectures sometimes with a gap of several weeks. Is it appropriate to wait for all supported arches to be available before creating a PR or do we let the arches trickle in as and when they become ready. Appreciate any thoughts/comments. Thanks !

**Comment by yosifkit** [comment]
What you've done in #6934 seems reasonable. The main drawback I see is that users trying to pull generic tags like `8-hotspot-bionic` will suddenly be unable to pull on certain architectures, but I don't have any great solutions other than waiting until specific architectures are available before updating.

The unfortunate side effect is that this will make some of our images like `tomcat` jump back and forth with their arches lists since we use parent image arches to determine arches for each tag.

**Comment by tianon** [comment]
We're quite a ways out at this point -- are those other architecture builds still pending?

**Comment by tianon** [comment]
We're over 50 days out now -- surely those ARM builds have finished by now, @dinogun? :pray:

**Comment by tianon** [comment]
@dinogun any word on those ARM builds? :disappointed:

**Comment by dinogun** [comment]
@tianon Sorry these builds are taking so long, the latest status of the arm32/arm64 builds are as [here](https://github.com/AdoptOpenJDK/TSC/issues/140).

We seem to have build issues with both arm32/arm64 for every release, as, in my (limited) understanding, these arch ports are not part of the mainline and it takes time to resolve merge issues and test failures. One [thought](https://github.com/AdoptOpenJDK/openjdk-docker/issues/303) was to deprecate the availability of these arches in the official images and have them in the unofficial adopt images. What would you prefer ?

**Comment by tianon** [comment]
Thanks for the links and the update :heart:

That's a hard question, and we don't have an official opinion on that, but IMO if they're officially a "second class citizen" upstream (and even further upstream in OpenJDK itself), it would probably make sense to drop them from here until they're more well supported. :disappointed:

For what it's worth, if ARM (32 *or* 64 bit) hardware availability is an issue, I'm sure you're already aware of the great folks at WorksOnArm (https://www.worksonarm.com/), but if not, I'd say they're worth reaching out to. :+1: :heart:

**Comment by sxa555** [comment]
FYI We've got a decent amount of arm capacity in the adoptopenjdk build farm so that isn't an issue that holds us up - the problem has been purely with some of the tagging of the repositories that we build from which is out of control of the AdoptOpenJDK project. We should be able to get arm32 out without any real problems for this month's release, but aarch64 may be subject to a (hopefully small this time!) delay.

**Comment by tianon** [comment]
Going to close this now as the original question is answered as well as I guess it really can be. :sweat_smile: :disappointed: :see_no_evil:
