### ISSUE TITLE
storm:2.1.0 is not available

### ISSUE THREAD

**Issue by 31z4** [docker-library/official-images#7024]
Looks like the build has failed and the image wasn't pushed to dockerhub. The image builds without issues locally.

Related to https://github.com/31z4/storm-docker/issues/25.

**Comment by yosifkit** [comment]
Looks like it keeps failing to download the `tar.gz`, but since it is quiet we don't know the exact cause: https://doi-janky.infosiftr.net/job/multiarch/view/images/view/storm/job/amd64/job/storm/

`wget -q http://www.apache.org/dist/storm/apache-storm-2.1.0/apache-storm-2.1.0.tar.gz`

We've found the direct `apache.org` servers to be unreliable sometimes (and they recommend not using them, but not all mirrors have the asc file), so we use a list of mirrors like https://github.com/docker-library/tomcat/pull/86 and https://github.com/docker-library/httpd/pull/79#issuecomment-335977951 to work around it.

**Comment by 31z4** [comment]
Thanks a lot @yosifkit!
