### ISSUE TITLE
Allow runit to manage unicorn and sidekiq processes

### ISSUE THREAD

**Issue by dosire** [docker-library/official-images#718]
See https://gitlab.com/gitlab-org/gitlab-ce/issues/1525#note_1171415 for the background of this request.

We understand the reason to have one process per docker container. But for Ruby applications such as Discourse, Chef server, and GitLab this is not practical nor beneficial. We propose to do the same thing as in https://registry.hub.docker.com/u/base/chef-server/dockerfile/ Is that OK?

**Comment by md5** [comment]
@dosire Can you elaborate on why it isn't practical or beneficial, possibly by quoting the relevant portion of the exchange you linked to?

**Comment by dosire** [comment]
General idea: https://blog.phusion.nl/2015/01/20/baseimage-docker-fat-containers-treating-containers-vms/

My formulation: As a system administrator, I wouldn't want to maintain seven different containers (e.g. data, logrotate, nginx, postgresql, redis, sidekiq, unicorn) and make sure the links between them work. I've had bad experiences where one dependent container stopped running or got reset by hand, and I've had to reset all the other containers to make the port links work again. While Docker has made significant improvements over the last 6 months, there are still rough edges. The reasons stated in the docker documentation for one process are: 'Decoupling applications into multiple containers makes it much easier to scale horizontally and reuse containers'. Horizontal scaling will be a next level in any case, but a single container can handle 10k+ Gitlab users. Container reuse is very hard, even our os packages installs all services in the opt directory because reusing os packages was too painful for most users. Our fellow big open source ruby app Discourse has the same problem, they also have one container, and no official images.

Specific problem: Omnibus-gitlab uses Runit to restart any of the GitLab processes in case one crashes. Our current workaround for Sidekiq memory leaks works by letting the Sidekiq terminate gracefully if its RSS gets too big. This assumes that something/somebody will then restart Sidekiq; with omnibus-gitlab that 'something' is Runit.

BTW https://gitlab.com/gitlab-org/gitlab-ce/issues/1525#note_1193010 I learned that base/chef-server is not "Official"

**Comment by dosire** [comment]
@md5 Hope you don't mind the brain dump above. Please let me know what your ideas are.

**Comment by cpuguy83** [comment]
Why is sidekiq running out of memory? This should not be happening. Is it something you've reported to https://github.com/mperham/sidekiq or is there a memory leak in one of your workers?

Also in a container, I don't think it makes sense to use omnibus since there is not going to be any conflicts with ruby versions, or even any problems getting ruby (and the right version of ruby) in the container.

**Comment by md5** [comment]
@dosire I don't mind at all. I'm too busy right now to digest it, but hopefully others can chime in based on what written and I can add any thoughts I have later (thanks @cpuguy83).

**Comment by dosire** [comment]
@cpuguy83 It is probably a problem with our code.

**Comment by dosire** [comment]
@cpuguy83 I agree that building an installation from source is possible. But it doesn't seem very user-friendly to require 7 linked containers to use GitLab.

**Comment by md5** [comment]
@dosire I agree with you that requiring 7 linked containers is not very user-friendly given the current state of Docker tooling. I think that something like Docker Compose could be used to allow those 7 containers to be run with a single command, but you're also right that the `--link` functionality can easily lead to situations where a bunch of containers need to be restarted because one crashes. There was talk at one point last year of a more dynamic "links v2" (cf. docker/docker#7468), but I'm not sure what the current state of that discussion is.

That being said, of the 7 container types you mention, I don't agree with using dedicated data containers as a general strategy since Docker volumes can be shared across containers without having a them attached to another throwaway container, but again, using Docker volumes right now is not very user-friendly in the face of app upgrades, etc. The current state of Docker volumes is collected under docker/docker#6496.

As for the other containers you mention, I don't know that having a `logrotate` container makes a lot of sense either, but again, the user-friendliness of Docker log handling leaves a lot to be desired and currently requires a lot of knowledge of how Docker logging works to be managed effectively, so I can understand your desire to include `logrotate` functionality in a turn-key Gitlab solution.

So that leaves `nginx`, `postgres`, `redis`, `unicorn`, and `sidekiq`. It doesn't sound like you're proposing including the first three in your combined container (and I definitely would keep them separate), so we're really just talking about going from N containers to N-1 containers. I don't think that's a huge gain in user friendliness.

As for combining your `unicorn` and `sidekiq` containers into a single container with `runit` or some other process manager, I don't think there's anything preventing you from doing that in a `gitlab/gitlab` container that's derived from the official `rails` image. All you'd need to do is add the process manager in your image and change the `CMD` from `bundle exec rails s` to `runit` (or `supervisor`, `forego`, etc).

Now if you want to eventually have an official `gitlab` container under `docker-library`, that might be a bit more controversial if the image includes a process manager, since I don't think there's precedent for that in the official images. Still, I don't think doing that in a `gitlab` container is going to meet as much resistance proposing it for `rails`, if that's in fact what you're doing (since it's not clear from your initial post or comments which image you're proposing to use `runit` for).

BTW, I'm speaking only for myself as someone who's an avid follower of the Docker official images; I don't have any formal involvement in the official image program, so @tianon, @yosifkit, @psftw, or @eave would be able to render a more official opinion.

**Comment by cpuguy83** [comment]
I also agree, it sucks.
There needs to be a better Hub interaction here.
Would be cool to be able to pull a full compose stack and use that directly.

**Comment by cpuguy83** [comment]
In a production scenario, an ops person would want to (or at least should want to) have these split up.
But for testing purposes, a single container is quite convenient.

**Comment by dosire** [comment]
@md5 Thanks for your reply, do I summarize your opinion correctly with:

1. OK to include logrotate
2. OK to use runit for unicorn and sidekiq
3. Nothing is likely to get merged under docker-library

In this case we'll go for a simple unofficial container like https://registry.hub.docker.com/u/base/chef-server/dockerfile/ I've just created https://gitlab.com/gitlab-org/gitlab-ce/commit/48f22a39e7275551c35cc84d11caf5df1a581e0e to do this.

Do you know how I can get the `gitlab` handle at DockerHub so we can indicate to users this comes from us?

**Comment by md5** [comment]
@dosire I think having an official `gitlab` container that just runs the main `rails s` or `rackup` container, along with a sample `docker-compose.yml` file in the docs that includes the `sidekiq` worker and other containers is in line with the current best practices for official images. You could then build on top of this `gitlab` container to create an "all-in-one" container that uses `runit` to manage separate processes as an unofficial image, or just create a separate container as you've already done.

I'm not a fan of doing `logrotate` by default, since that implies that your logs are going to a file instead of following the Docker recommendations of sending all logs to STDOUT/STDERR (to allow the use of the `docker logs` command), but I do understand the desire to have a turn-key solution.

As for making an official `gitlab` image, which I think is what you're asking, take a look at these docs: https://docs.docker.com/docker-hub/official_repos/

If instead you're saying that the current [`gitlab`](https://registry.hub.docker.com/repos/gitlab/) is not actually controlled by Gitlab, then you'd have to take that up with support@docker.com.

**Comment by md5** [comment]
Also, I'd probably name the all-in-one container something like `gitlab/gitlab-combined` instead of `gitlab/gitlab` to avoid confusion with any potential `gitlab` container you might maintainer under the Official Images program.

**Comment by dosire** [comment]
@md5 Thanks for your answer. I'll take the suggestions how to make the official container into account.

I meant that the current `gitlab` is not controlled by us and will contact support.

I propose the following naming, hope this is acceptable for you:

1. The combined container is named gitlab/gitlab-ce
3. The separate app and data containers are gitlan/gitlab-app and gitlab/gitlab-data
2. The official containers will be gitlab/gitlab-rails and gitlab/gitlab-sidekiq

**Comment by dosire** [comment]
I've created a feature request for the official GitLab image: http://feedback.gitlab.com/forums/176466-general/suggestions/7860288-official-docker-image

Email to support is send.

**Comment by md5** [comment]
:+1: 

Good luck getting control of `gitlab/*`. Makes me curious who created this: https://registry.hub.docker.com/u/gitlab/registry/

**Comment by dosire** [comment]
@md5 me too

**Comment by dosire** [comment]
FYI We got control of gitlab/ and now have an official image on https://registry.hub.docker.com/u/gitlab/gitlab-ce/
