### ISSUE TITLE
Request to re-build ubuntu:18.04 image with latest updates

### ISSUE THREAD

**Issue by jayasg12** [docker-library/official-images#7263]
We see ubuntu image is not re-built with a fix for this vulnerability -> https://github.com/ibmruntimes/ci.docker/issues/82

docker run -it ubuntu:18.04 /bin/bash
root@c08dadf79ba3:/# apt-cache policy libgnutls30
libgnutls30:
  Installed: 3.5.18-1ubuntu1.1
  Candidate: 3.5.18-1ubuntu1.1
  Version table:
 *** 3.5.18-1ubuntu1.1 100
        100 /var/lib/dpkg/status

**Comment by yosifkit** [comment]
The last Ubuntu build was https://github.com/docker-library/official-images/pull/7147, so 27 days ago and would likely be built in the next week. We strive to publish updated images at least monthly for Debian and Ubuntu. (https://github.com/docker-library/faq/#why-does-my-security-scanner-show-that-an-image-has-cves)

I don't see this "vulnerability" important enough to rush a new update, since it only marks SHA1 as insecure for certificate signing (https://usn.ubuntu.com/4233-1/).  But that would really be up to the Ubuntu maintainer @mwhudson.

>   \* SECURITY UPDATE: Mark SHA1 as insecure for certificate signing
>    \- debian/patches/insecuresha1-*.patch: backport upstream patches to
>      allow marking SHA1 as insecure, but only for certificate signing.
>
> \-https://launchpad.net/ubuntu/+source/gnutls28/3.5.18-1ubuntu1.2

**Comment by wglambert** [comment]
Ubuntu was updated 2 days ago https://github.com/docker-library/official-images/pull/7280

**Comment by IdanAdar** [comment]
Do we need a separate ticket for CVE-2019-13627?

**Comment by IdanAdar** [comment]
The ibmjava image has this: 

```
docker run -it test:1 apt policy libgcrypt20                              
libgcrypt20:
  Installed: 1.8.1-4ubuntu1.1
  Candidate: 1.8.1-4ubuntu1.1
  Version table:
 *** 1.8.1-4ubuntu1.1 100
        100 /var/lib/dpkg/status
```

**Comment by davidkarlsen** [comment]
I can't find an updated `20200115` tag? https://hub.docker.com/_/ubuntu/?tab=tags

**Comment by yosifkit** [comment]
> Do we need a separate ticket for CVE-2019-13627?

Not here unless it is applicable and actionable on more than just Ubuntu; any issues with the Ubuntu base images should really be filed in their tracker (https://bugs.launchpad.net/cloud-images), as mentioned in the Docker Hub description.

> I can't find an updated `20200115` tag for bionic? https://hub.docker.com/_/ubuntu/?tab=tags

There is no `20200115` for 18.04; looking at https://github.com/docker-library/official-images/pull/7280 it should be `bionic-20200112`.
