### ISSUE TITLE
debian:lenny ?

### ISSUE THREAD

**Issue by mcandre** [docker-library/official-images#731]
Could we please upload Debian 5.0 "lenny" for more backwards compatibility?

**Comment by tianon** [comment]
Since `lenny` is only available via http://archive.debian.org (and will receive no further updates), I'm afraid it won't be added as a supported tag to the official `debian` image.

However, you should be able to take the `mkimage.sh` script that builds the official Debian image (https://github.com/docker/docker/blob/master/contrib/mkimage.sh and https://github.com/docker/docker/blob/master/contrib/mkimage/debootstrap) and use it to build a `lenny` variant fairly easily (in theory):
```console
$ ./mkimage.sh -t debian:lenny debootstrap --variant=minbase --components=main --include=inetutils-ping,iproute lenny http://archive.debian.org/debian
...
```

In practice, you run into errors due to the older APT in Lenny not supporting some of the configuration changes we make: (which is another reason it can't easily be supported here officially)
```
E: Syntax error /etc/apt/apt.conf.d/docker-autoremove-suggests:16: Extra junk after value
```

A simpler alternative would be to just make a `debootstrap` of lenny and import it directly:
```console
$ debootstrap --variant=minbase --components=main --include=inetutils-ping,iproute lenny some-directory http://archive.debian.org/debian
...
$ tar -cC some-directory . | docker import - debian:lenny
```

**Comment by mcandre** [comment]
Thanks for the tip! I've done just that with mcandre/docker-debian:lenny.
