### ISSUE TITLE
Latest Debian build failed. 

### ISSUE THREAD

**Issue by burtininkai** [docker-library/official-images#8495]
Howdy

Latest debian build failed. If I pull latest debian, it's looks the same as buster-20200720

<img width="984" alt="Screenshot 2020-08-04 at 11 42 41" src="https://user-images.githubusercontent.com/989645/89273076-bcfde780-d647-11ea-9ad7-1c7f841119ad.png">

also can't pull the latest tags
<img width="555" alt="Screenshot 2020-08-04 at 11 44 23" src="https://user-images.githubusercontent.com/989645/89273180-e0c12d80-d647-11ea-8674-c7dc9527689a.png">

**Comment by tianon** [comment]
I don't think it failed, I think it's just been stuck behind a lot of `python` tag builds (which was merged shortly before) and thus hasn't quite built yet.


For future reference, https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what may be a useful resource.

A lot of times, `amd64` ends up being one of our slower architectures partly because it has the most supported image/tag combinations (to illustrate, all but one image in the program supports `amd64`, which can't be said about any other architecture we support), and performance of commands like `docker images` suffers dramatically when the number of images on a single host increases beyond "normal" amounts.  It also isn't a particularly beefy VM (which is unfortunate, but a bit outside our control).

**Comment by tianon** [comment]
It's up now. :smile:

**Comment by burtininkai** [comment]
Thx. Next time will check in jenkins.
