### ISSUE TITLE
nginx:1.9 image not working with bcrypt encryption

### ISSUE THREAD

**Issue by Wombasta** [docker-library/official-images#860]
The issue is discussed here: https://github.com/docker/distribution/issues/655
Generally, the issue is that nginx in provided image does not let to use bcrypt encrypted htpasswd created with -B key (`htpasswd -B ...` ). Most probably glibc package of image's OS (Debian Jessie) does not let to use bcrypt encryption.
For example, the Basic Authentication manual leads to an auth error. Everything works good without using -B key when generating htpasswd but using standard apache md5 algorithm is insecure.

**Comment by tianon** [comment]
This really ought to be reported over at
https://github.com/nginxinc/docker-nginx/issues, although I don't know of
any reason this shouldn't work if upstream nginx supports it, since the
image just installs the "nginx" package from upstream's APT repository.

**Comment by stevvooe** [comment]
Filed nginxinc/docker-nginx#29.

**Comment by stevvooe** [comment]
Looks like #29 has been closed. Can anyone give this a try?

**Comment by fabfuel** [comment]
It works fine with the current `nginx:alpine` tag.
But it still fails with the current `nginx:stable` or `nginx:latest` tags.

**Comment by tianon** [comment]
Thanks @fabfuel! :+1:

**Comment by TristanCP** [comment]
"It still fails with the current nginx:stable or nginx:latest tags" and you conclude you can close the issue ?

**Comment by stevvooe** [comment]
@TristanCP Try it with less snark. Remember that there is always a reason things are inconvenient.

The reason this doesn't work with stable and latest is due to the exclusion of bcrypt from the base images. There is not much to be done without breaking people.

@tianon Would it be possible to get bcrypt into the base image? Can we reach out to the nginx team to get this worked out?

**Comment by yosifkit** [comment]
> Would it be possible to get bcrypt into the base image? Can we reach out to the nginx team to get this worked out?

The nginx upstream issue is nginxinc/docker-nginx#29. My reading of that issue brings me to the conclusion that bcrypt is not in Debian's libc (or even upstream glibc; [upstream bug to add bcrypt](https://sourceware.org/bugzilla/show_bug.cgi?id=16814)) so we can't really do anything about it, but the recommended workaround is to use the alpine based image since it does have bcrypt.

**Comment by TristanCP** [comment]
@stevvooe Sorry I was just protesting against the closing process of some issues without giving any explanation. Please don't do this, it forces all people consulting these issues to do research to understand why it may be considered as "closed", instead of just reading the final comment of the closer.

Here I'd say : "bcrypt it not  available in Debian image which is our base image for all official images. As a work around, if you need strong encryption on Debian, you can use "mkpasswd -m sha-512" to generate your passwords, or switch to our alpine base image".
