### ISSUE TITLE
Make a duplicate copy of an image, independent of the original image

### ISSUE THREAD

**Issue by fahadchauhan** [docker-library/official-images#8653]
#Scenario 
We have multiple images that we have committed from containers, however we are unable to make an independent copy of our latest image.

#Steps Tried:
We have attempted to remove the previous images, however they appear to have child images existing in the form of previous images and hence docker does not allow us to delete them.

We have attempted to remove the dangling images as well, but to no avail.

**Comment by wglambert** [comment]
I would try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum. 
And providing specific error messages for what issues you're encountering would help with troubleshooting
