### ISSUE TITLE
I need  add coredns to official images.

### ISSUE THREAD

**Issue by duchuanLX** [docker-library/official-images#9534]
i try coredns support mips64le.
https://github.com/coredns/coredns/issues/4434

i get some usefull information,coredns will support mips64le on new version 1.18.1.
https://github.com/coredns/coredns/pull/4421

now coredns  support architectures such as amd64,arm,arm64,mips64le,ppc64le,s390x

i need coredns on mips64le official images 
https://hub.docker.com/u/mips64le

please add coredns to official images

@tianon
@jsternberg

**Comment by tianon** [comment]
We won't be adding `coredns` without the consent and participation of the `coredns` upstream project.

That being said, we'd welcome a new image proposal from them (in the form of a PR which follows the contribution guidelines outlined in this repository's README).

It looks like your particular desire will be fixed with their next release in the images they directly publish, however.

**Comment by duchuanLX** [comment]
@tianon

I have already contacted your coredns community, and I will reply to any news in time. Thanks for your guidance.
